# -*- coding: utf-8 -*-
"""sri ram sir model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSMjMo_q73QXuSNjZMzD7NjcmoDbh15V
"""

import matplotlib.pyplot as plt
import numpy as np

# --- Data from the paper (Table: Model Calibration indicators) ---
labels = ['Prevalence\n2020', 'Notification\n2019', 'Mortality\n2015']

# Data (observed) — central estimate and 95% CI (lo, hi)
data_central = [312, 94, 28]
data_lo      = [286, 80, 20]
data_hi      = [337, 108, 36]

# Model (calibrated output) — approx read from Figure 2 (replace with your real values)
model_central = [320, 88, 26]
model_lo      = [300, 78, 18]
model_hi      = [340, 98, 34]

# Convert to (value, lower_err, upper_err) for errorbar plotting
data_err  = [np.array(data_central) - np.array(data_lo),
             np.array(data_hi) - np.array(data_central)]
model_err = [np.array(model_central) - np.array(model_lo),
             np.array(model_hi) - np.array(model_central)]

x = np.arange(len(labels))
offset = 0.08  # horizontal dodge so Data/Model dots don't overlap

fig, ax = plt.subplots(figsize=(5, 5))

ax.errorbar(x - offset, data_central, yerr=data_err, fmt='o', color='red',
            capsize=4, label='Data', markersize=7)
ax.errorbar(x + offset, model_central, yerr=model_err, fmt='o', color='blue',
            capsize=4, label='Model', markersize=7)

ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_ylabel('Value')
ax.set_title('Population rates')
ax.set_ylim(0, 350)
ax.legend(loc='upper right')
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig('figure2_population_rates.png', dpi=300)
plt.show()

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# 1. PARAMETERS  (posterior medians, Table S1)
# ---------------------------------------------------------------------------
P = dict(
    beta      = 4.4,     # rate-of-transmission (Table S1 calls it "b")
    mu        = 1/70,    # background mortality (and birth rate, to hold N~1)
    u         = 0.07,    # Lf -> I progression
    v         = 0.85,    # Lf -> Ls stabilisation
    w         = 0.0035,  # Ls -> I reactivation
    c         = 0.031,   # LTBI self-clearance (Lf,Ls -> U)
    sigma     = 0.17,    # self-cure from active TB
    muTB      = 0.07,    # TB mortality, untreated
    muTB_pu   = 0.103,   # TB mortality, on public treatment
    muTB_pr   = 0.051,   # TB mortality, on private treatment
    h         = 0.38,    # protection from reinfection (recovered classes)
    rho_lo    = 0.083,   # relapse rate, low-risk
    rho_hi    = 0.14,    # relapse rate, high-risk
    rho       = 0.0015,  # relapse rate, long-term stabilised
    s         = 0.5,     # stabilisation rate Rhi/Rlo -> R
    delta     = 52,      # rate of "offering" diagnosis once presented (~weekly)
    pDx_pu    = 0.67,    # prob. successful public dx+tx initiation per visit
    pDx_pr    = 0.64,    # prob. successful private dx+tx initiation per visit
    tau       = 2.0,     # treatment completion rate (~6 month course)
    eps_pu    = 0.52,    # treatment interruption rate, public
    eps_pr    = 2.2,     # treatment interruption rate, private
    gamma_tilde = 4.9,   # careseeking rate, 2nd+ attempts (const 2011->2020)
    # time-varying pieces (linear 2011->2020, then held flat):
    gamma_2011 = 0.30,
    gamma_2020 = 0.55,
    p_2011     = 0.50,
    p_2020     = 0.60,
)

T0, T1 = 2011.0, 2020.0  # window over which gamma(t), p(t) ramp linearly


def linear_ramp(t, y0, y1, t0=T0, t1=T1):
    """Linear interpolation from y0 at t0 to y1 at t1; flat before/after."""
    if t <= t0:
        return y0
    if t >= t1:
        return y1
    return y0 + (y1 - y0) * (t - t0) / (t1 - t0)


def beta_t(t, beta_base):
    """
    50% reduction in transmission during:
      - national lockdown: Apr-Jul 2020
      - delta wave:        May-Sep 2021
    (as stated in the Methods / Fig S3 discussion)
    """
    if (2020 + 3/12 <= t <= 2020 + 7/12) or (2021 + 4/12 <= t <= 2021 + 9/12):
        return 0.5 * beta_base
    return beta_base


def a_t(t):
    """
    Active-case-finding rate. The paper does not give a closed-form a(t);
    it is calibrated against annual ACF notification counts (Table:
    26,781 in 2017 ... 73,772 in 2021). Left at 0 here -- see README notes
    at the bottom of this file for how to extend it.
    """
    return 0.0


def rhs(t, y, P):
    U, Lf, Ls, I, Dpu, Dpr, E, Tpu, Tpr, Rlo, Rhi, R = y

    gamma = linear_ramp(t, P['gamma_2011'], P['gamma_2020'])
    p     = linear_ramp(t, P['p_2011'],     P['p_2020'])
    beta  = beta_t(t, P['beta'])
    gt    = P['gamma_tilde']
    a     = a_t(t)
    mu    = P['mu']

    lam = beta * (I + E + Dpr + Dpu)                       # force of infection
    b   = mu                                                # birth = death -> N const

    dU   = b - (lam + mu) * U + P['c'] * (Lf + Ls)
    dLf  = lam * (U + (1 - P['h']) * (Rhi + Rlo + R)) \
           - (P['u'] + P['v'] + P['c'] + mu) * Lf
    dLs  = P['v'] * Lf - (P['w'] + P['c'] + mu) * Ls
    dI   = P['u'] * Lf + P['w'] * Ls \
           + (P['rho_hi'] * Rhi + P['rho_lo'] * Rlo + P['rho'] * R) \
           - (gamma + P['muTB'] + P['sigma'] + a + mu) * I
    dDpu = p * gamma * I + p * gt * E \
           - (P['delta'] + P['muTB'] + P['sigma'] + mu) * Dpu
    dDpr = (1 - p) * gamma * I + (1 - p) * gt * E \
           - (P['delta'] + P['muTB'] + P['sigma'] + mu) * Dpr
    dE   = P['delta'] * (1 - P['pDx_pu']) * Dpu \
           + P['delta'] * (1 - P['pDx_pr']) * Dpr \
           - (P['muTB'] + P['sigma'] + gt + mu) * E
    dTpu = P['delta'] * P['pDx_pu'] * Dpu + a * I \
           - (P['tau'] + P['muTB_pu'] + P['eps_pu'] + mu) * Tpu
    dTpr = P['delta'] * P['pDx_pr'] * Dpr \
           - (P['tau'] + P['muTB_pr'] + P['eps_pr'] + mu) * Tpr
    dRlo = P['tau'] * (Tpu + Tpr) \
           - ((1 - P['h']) * lam + P['rho_lo'] + mu + P['s']) * Rlo
    dRhi = P['eps_pu'] * Tpu + P['eps_pr'] * Tpr \
           - ((1 - P['h']) * lam + P['rho_hi'] + mu + P['s']) * Rhi
    dR   = P['s'] * (Rlo + Rhi) - ((1 - P['h']) * lam + P['rho'] + mu) * R

    return [dU, dLf, dLs, dI, dDpu, dDpr, dE, dTpu, dTpr, dRlo, dRhi, dR]


# ---------------------------------------------------------------------------
# 2. EQUILIBRATE pre-2011, then run 2011 -> 2022
# ---------------------------------------------------------------------------
y0_guess = [0.65, 0.01, 0.25, 0.003, 0.0005, 0.0005, 0.0005,
            0.0002, 0.0002, 0.01, 0.01, 0.03]
y0_guess = np.array(y0_guess) / sum(y0_guess)   # normalise to sum to 1

# burn-in: hold gamma/p/beta at their 2011 starting values for 150 years
# to reach a stable pre-2011 epidemiological equilibrium
def rhs_burnin(t, y):
    Pb = dict(P)
    Pb['gamma_2011'] = Pb['gamma_2020'] = P['gamma_2011']
    Pb['p_2011']     = Pb['p_2020']     = P['p_2011']
    return rhs(t, y, Pb)

burn = solve_ivp(rhs_burnin, [1861, 2011], y0_guess, method='LSODA',
                  max_step=1.0, rtol=1e-8, atol=1e-10)
y_2011 = burn.y[:, -1]

sol = solve_ivp(lambda t, y: rhs(t, y, P), [2011, 2022.5], y_2011,
                 method='LSODA', dense_output=True, max_step=0.02,
                 rtol=1e-8, atol=1e-12)

# ---------------------------------------------------------------------------
# 3. EXTRACT THE THREE FIGURE-2 QUANTITIES
# ---------------------------------------------------------------------------
def state_at(year):
    return sol.sol(year)

def annual_flow_integral(year, flow_fn, n=200):
    """Integrate a flow-rate function (per-year rate) over one calendar year
    using the dense ODE solution, via Simpson's rule on a fine grid."""
    ts = np.linspace(year, year + 1, n)
    ys = sol.sol(ts)
    vals = np.array([flow_fn(ts[i], ys[:, i]) for i in range(n)])
    return np.trapezoid(vals, ts)

# ---- Prevalence, 2020 (mid-year snapshot) ----
y_2020 = state_at(2020.5)
U, Lf, Ls, I, Dpu, Dpr, E, Tpu, Tpr, Rlo, Rhi, R = y_2020
prevalence_2020 = (I + Dpu + Dpr + E) * 100000
print(f"Model prevalence, 2020 (per 100,000): {prevalence_2020:.0f}")

# ---- Public-sector notification, 2019 (new+relapse treatment initiations) ----
def pu_notification_rate(t, y):
    Uc, Lfc, Lsc, Ic, Dpuc, Dprc, Ec, Tpuc, Tprc, Rloc, Rhic, Rc = y
    return P['delta'] * P['pDx_pu'] * Dpuc + a_t(t) * Ic

pu_notif_2019 = annual_flow_integral(2019, pu_notification_rate) * 100000
print(f"Model public-sector notification, 2019 (per 100,000): {pu_notif_2019:.0f}")

# ---- Mortality, 2015 (TB deaths per year, all compartments) ----
def mortality_rate(t, y):
    Uc, Lfc, Lsc, Ic, Dpuc, Dprc, Ec, Tpuc, Tprc, Rloc, Rhic, Rc = y
    # deaths occur from I, Dpu, Dpr, E at rate muTB; from Tpu at muTB_pu; Tpr at muTB_pr
    return (P['muTB'] * (Ic + Dpuc + Dprc + Ec)
            + P['muTB_pu'] * Tpuc + P['muTB_pr'] * Tprc)

mortality_2015 = annual_flow_integral(2015, mortality_rate) * 100000
print(f"Model mortality, 2015 (per 100,000): {mortality_2015:.0f}")

# ---------------------------------------------------------------------------
# 4. PLOT (Figure 2, left panel: "Population rates")
# ---------------------------------------------------------------------------
labels = ['Prevalence\n2020', 'Notification\n2019', 'Mortality\n2015']
data_central = [312, 94, 28]
data_lo      = [286, 80, 20]
data_hi      = [337, 108, 36]

model_central = [prevalence_2020, pu_notif_2019, mortality_2015]

x = np.arange(len(labels))
offset = 0.08
fig, ax = plt.subplots(figsize=(5, 5))
ax.errorbar(x - offset, data_central,
            yerr=[np.array(data_central) - np.array(data_lo),
                  np.array(data_hi) - np.array(data_central)],
            fmt='o', color='red', capsize=4, label='Data', markersize=7)
ax.plot(x + offset, model_central, 'o', color='blue', markersize=7, label='Model')

ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_ylabel('Value')
ax.set_title('Population rates (point-estimate reconstruction)')
ax.set_ylim(0, 350)
ax.legend(loc='upper right')
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.show()

"""
Reimplementation of the compartmental TB model in:
Mandal S, Rao R, Joshi R. "Estimating the Burden of Tuberculosis in India:
A Modelling Study." Indian J Community Med 2023;48:436-42.

This version adds an UNCERTAINTY BAND for the model outputs, so the
"Model" points in the Figure 2 plot get a lo/mid/hi just like "Data" does.

METHOD USED (read this before trusting the numbers):
  The paper gets its Model lo/mid/hi from full Bayesian MCMC calibration --
  every uncertain parameter is jointly updated against ALL calibration
  targets at once, and the reported 95% CrI is the 2.5th/97.5th percentile
  of that joint posterior.

  Reproducing that exactly requires writing a log-posterior (beta /
  log-normal likelihoods against each Data target) and running an
  MCMC sampler (e.g. emcee, or a hand-rolled Metropolis-Hastings) -- that
  is a bigger undertaking than what's below.

  What THIS script does instead is simpler and faster to run: it takes
  the marginal 95% CI already reported for each parameter in Table S1,
  treats each one as an independent Normal distribution, draws N random
  parameter sets from those independent distributions ("Monte Carlo
  forward uncertainty propagation"), runs the full ODE model once per
  draw, and reports the 2.5th/50th/97.5th percentiles of the resulting
  simulated outputs as Model lo/mid/hi.

  This is NOT the same as MCMC calibration -- it does not use the Data
  targets to constrain the parameter draws at all, and it ignores the
  correlations between parameters that a joint posterior would have.
  It will therefore give a wider and differently-centred band than the
  paper's. But it is the correct, standard way to answer "how much does
  my model output vary given the parameter uncertainty I was told about",
  and it's the natural stepping stone toward full MCMC (see the bottom
  of this file for how that would differ in code structure).
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

rng = np.random.default_rng(42)   # fixed seed -> reproducible draws

# ---------------------------------------------------------------------------
# 1. PARAMETER CENTRAL VALUES + 95% CI  (Table S1)
#    dist: 'normal'  -> sample ~ N(mid, sd), sd = (hi-lo)/(2*1.96), clipped
#          'fixed'   -> no uncertainty reported; held constant
# ---------------------------------------------------------------------------
PARAM_SPECS = {
    # name        : (mid,     lo,      hi,      dist,    clip_lo, clip_hi
    'beta':         (4.4,     3.4,     6.2,     'normal', 0,      None),
    'u':            (0.07,    0.01,    0.13,    'normal', 0,      None),
    'v':            (0.85,    0.78,    0.95,    'normal', 0,      1),
    'w':            (0.0035,  0.0004,  0.0061,  'normal', 0,      None),
    'c':            (0.031,   0.022,   0.035,   'normal', 0,      None),
    'muTB':         (0.07,    0.05,    0.10,    'normal', 0,      None),
    'sigma':        (0.17,    0.13,    0.21,    'normal', 0,      None),
    'h':            (0.38,    0.13,    0.73,    'normal', 0,      1),
    'rho_lo':       (0.083,   0.065,   0.106,   'normal', 0,      None),
    'rho_hi':       (0.14,    0.11,    0.17,    'normal', 0,      None),
    'rho':          (0.0015,  0.0011,  0.0018,  'normal', 0,      None),
    'gamma_2011':   (0.30,    0.19,    0.44,    'normal', 0,      None),
    'gamma_2020':   (0.55,    0.46,    0.71,    'normal', 0,      None),
    'gamma_tilde':  (4.9,     0.8,     12.4,    'normal', 0,      None),
    'p_2011':       (0.50,    0.0,     0.98,    'normal', 0,      1),
    'p_2020':       (0.60,    0.40,    0.80,    'normal', 0,      1),
    'pDx_pu':       (0.67,    0.34,    0.89,    'normal', 0,      1),
    'pDx_pr':       (0.64,    0.33,    0.88,    'normal', 0,      1),
    'eps_pu':       (0.52,    0.26,    0.66,    'normal', 0,      None),
    'eps_pr':       (2.2,     0.9,     2.9,     'normal', 0,      None),
    # fixed (no CI reported in Table S1):
    'mu':           (1/70,    None,    None,    'fixed',  None,   None),
    'muTB_pu':      (0.103,   None,    None,    'fixed',  None,   None),
    'muTB_pr':      (0.051,   None,    None,    'fixed',  None,   None),
    'delta':        (52,      None,    None,    'fixed',  None,   None),
    'tau':          (2.0,     None,    None,    'fixed',  None,   None),
    's':            (0.5,     None,    None,    'fixed',  None,   None),
}


def sample_params():
    """Draw one random parameter set from the specs above."""
    P = {}
    for name, (mid, lo, hi, dist, clo, chi) in PARAM_SPECS.items():
        if dist == 'fixed':
            P[name] = mid
        else:  # normal, from 95% CI
            sd = (hi - lo) / (2 * 1.96)
            val = rng.normal(mid, sd)
            if clo is not None:
                val = max(val, clo)
            if chi is not None:
                val = min(val, chi)
            P[name] = val
    return P


T0, T1 = 2011.0, 2020.0

def linear_ramp(t, y0, y1, t0=T0, t1=T1):
    if t <= t0:
        return y0
    if t >= t1:
        return y1
    return y0 + (y1 - y0) * (t - t0) / (t1 - t0)


def beta_t(t, beta_base):
    if (2020 + 3/12 <= t <= 2020 + 7/12) or (2021 + 4/12 <= t <= 2021 + 9/12):
        return 0.5 * beta_base
    return beta_base


def a_t(t):
    """Active-case-finding rate -- not given in closed form; left at 0."""
    return 0.0


def rhs(t, y, P):
    U, Lf, Ls, I, Dpu, Dpr, E, Tpu, Tpr, Rlo, Rhi, R = y

    gamma = linear_ramp(t, P['gamma_2011'], P['gamma_2020'])
    p     = linear_ramp(t, P['p_2011'],     P['p_2020'])
    beta  = beta_t(t, P['beta'])
    gt    = P['gamma_tilde']
    a     = a_t(t)
    mu    = P['mu']

    lam = beta * (I + E + Dpr + Dpu)
    b   = mu

    dU   = b - (lam + mu) * U + P['c'] * (Lf + Ls)
    dLf  = lam * (U + (1 - P['h']) * (Rhi + Rlo + R)) \
           - (P['u'] + P['v'] + P['c'] + mu) * Lf
    dLs  = P['v'] * Lf - (P['w'] + P['c'] + mu) * Ls
    dI   = P['u'] * Lf + P['w'] * Ls \
           + (P['rho_hi'] * Rhi + P['rho_lo'] * Rlo + P['rho'] * R) \
           - (gamma + P['muTB'] + P['sigma'] + a + mu) * I
    dDpu = p * gamma * I + p * gt * E \
           - (P['delta'] + P['muTB'] + P['sigma'] + mu) * Dpu
    dDpr = (1 - p) * gamma * I + (1 - p) * gt * E \
           - (P['delta'] + P['muTB'] + P['sigma'] + mu) * Dpr
    dE   = P['delta'] * (1 - P['pDx_pu']) * Dpu \
           + P['delta'] * (1 - P['pDx_pr']) * Dpr \
           - (P['muTB'] + P['sigma'] + gt + mu) * E
    dTpu = P['delta'] * P['pDx_pu'] * Dpu + a * I \
           - (P['tau'] + P['muTB_pu'] + P['eps_pu'] + mu) * Tpu
    dTpr = P['delta'] * P['pDx_pr'] * Dpr \
           - (P['tau'] + P['muTB_pr'] + P['eps_pr'] + mu) * Tpr
    dRlo = P['tau'] * (Tpu + Tpr) \
           - ((1 - P['h']) * lam + P['rho_lo'] + mu + P['s']) * Rlo
    dRhi = P['eps_pu'] * Tpu + P['eps_pr'] * Tpr \
           - ((1 - P['h']) * lam + P['rho_hi'] + mu + P['s']) * Rhi
    dR   = P['s'] * (Rlo + Rhi) - ((1 - P['h']) * lam + P['rho'] + mu) * R

    return [dU, dLf, dLs, dI, dDpu, dDpr, dE, dTpu, dTpr, dRlo, dRhi, dR]


y0_guess = np.array([0.65, 0.01, 0.25, 0.003, 0.0005, 0.0005, 0.0005,
                      0.0002, 0.0002, 0.01, 0.01, 0.03])
y0_guess = y0_guess / y0_guess.sum()


def run_model(P):
    """Run one full simulation for parameter set P; return
    (prevalence_2020, pu_notif_2019, mortality_2015), all per 100,000."""

    def rhs_burnin(t, y):
        Pb = dict(P)
        Pb['gamma_2011'] = Pb['gamma_2020'] = P['gamma_2011']
        Pb['p_2011']     = Pb['p_2020']     = P['p_2011']
        return rhs(t, y, Pb)

    burn = solve_ivp(rhs_burnin, [1861, 2011], y0_guess, method='LSODA',
                      max_step=1.0, rtol=1e-6, atol=1e-9)
    y_2011 = burn.y[:, -1]

    sol = solve_ivp(lambda t, y: rhs(t, y, P), [2011, 2022.5], y_2011,
                     method='LSODA', dense_output=True, max_step=0.05,
                     rtol=1e-6, atol=1e-10)

    def annual_flow_integral(year, flow_fn, n=100):
        ts = np.linspace(year, year + 1, n)
        ys = sol.sol(ts)
        vals = np.array([flow_fn(ts[i], ys[:, i]) for i in range(n)])
        return np.trapezoid(vals, ts)

    U, Lf, Ls, I, Dpu, Dpr, E, Tpu, Tpr, Rlo, Rhi, R = sol.sol(2020.5)
    prevalence_2020 = (I + Dpu + Dpr + E) * 100000

    def pu_notification_rate(t, y):
        _, _, _, Ic, Dpuc, *_ = y
        return P['delta'] * P['pDx_pu'] * Dpuc + a_t(t) * Ic

    pu_notif_2019 = annual_flow_integral(2019, pu_notification_rate) * 100000

    def mortality_rate(t, y):
        _, _, _, Ic, Dpuc, Dprc, Ec, Tpuc, Tprc, *_ = y
        return (P['muTB'] * (Ic + Dpuc + Dprc + Ec)
                + P['muTB_pu'] * Tpuc + P['muTB_pr'] * Tprc)

    mortality_2015 = annual_flow_integral(2015, mortality_rate) * 100000

    return prevalence_2020, pu_notif_2019, mortality_2015


# ---------------------------------------------------------------------------
# 2. MONTE CARLO LOOP
# ---------------------------------------------------------------------------
N = 200
results = np.zeros((N, 3))
n_failed = 0

for i in range(N):
    P = sample_params()
    try:
        results[i] = run_model(P)
    except Exception:
        results[i] = np.nan
        n_failed += 1
    if (i + 1) % 50 == 0:
        print(f"  {i+1}/{N} runs done")

results = results[~np.isnan(results).any(axis=1)]
print(f"Completed {len(results)}/{N} runs ({n_failed} failed)")

prev_lo, prev_mid, prev_hi = np.percentile(results[:, 0], [2.5, 50, 97.5])
notif_lo, notif_mid, notif_hi = np.percentile(results[:, 1], [2.5, 50, 97.5])
mort_lo, mort_mid, mort_hi = np.percentile(results[:, 2], [2.5, 50, 97.5])

print(f"Model prevalence 2020:      {prev_mid:.0f} ({prev_lo:.0f} - {prev_hi:.0f})")
print(f"Model notification 2019:    {notif_mid:.0f} ({notif_lo:.0f} - {notif_hi:.0f})")
print(f"Model mortality 2015:       {mort_mid:.0f} ({mort_lo:.0f} - {mort_hi:.0f})")

# ---------------------------------------------------------------------------
# 3. PLOT -- Data AND Model both with error bars
# ---------------------------------------------------------------------------
labels = ['Prevalence\n2020', 'Notification\n2019', 'Mortality\n2015']

data_central = np.array([312, 94, 28])
data_lo      = np.array([286, 80, 20])
data_hi      = np.array([337, 108, 36])

model_central = np.array([prev_mid, notif_mid, mort_mid])
model_lo      = np.array([prev_lo, notif_lo, mort_lo])
model_hi      = np.array([prev_hi, notif_hi, mort_hi])

x = np.arange(len(labels))
offset = 0.08

fig, ax = plt.subplots(figsize=(5, 5))
ax.errorbar(x - offset, data_central,
            yerr=[data_central - data_lo, data_hi - data_central],
            fmt='o', color='red', capsize=4, label='Data', markersize=7)
ax.errorbar(x + offset, model_central,
            yerr=[model_central - model_lo, model_hi - model_central],
            fmt='o', color='blue', capsize=4, label='Model', markersize=7)

ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.set_ylabel('Value')
ax.set_title('Population rates (Monte Carlo uncertainty)')
ax.set_ylim(0, max(model_hi.max(), data_hi.max()) * 1.1)
ax.legend(loc='upper right')
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np

# ---------------------------------------------------------------------------
# 1. DOWNLOAD + ASSEMBLE THE NATIONAL-LEVEL INDIA TIME SERIES
# ---------------------------------------------------------------------------
BASE_URL = "https://www.gstatic.com/covid19/mobility/{year}_IN_Region_Mobility_Report.csv"
YEARS = [2020, 2021, 2022]

COLS = [
    "country_region", "sub_region_1", "sub_region_2", "date",
    "retail_and_recreation_percent_change_from_baseline",
    "transit_stations_percent_change_from_baseline",
    "parks_percent_change_from_baseline",
    "workplaces_percent_change_from_baseline",
]

frames = []
for year in YEARS:
    url = BASE_URL.format(year=year)
    df = pd.read_csv(url, usecols=COLS, low_memory=False)
    frames.append(df)

raw = pd.concat(frames, ignore_index=True)

# National-level rows only: no state (sub_region_1) or district (sub_region_2)
national = raw[raw['sub_region_1'].isna() & raw['sub_region_2'].isna()].copy()
national['date'] = pd.to_datetime(national['date'])
national = national.sort_values('date').reset_index(drop=True)

rename = {
    'retail_and_recreation_percent_change_from_baseline': 'retail_and_recreation',
    'transit_stations_percent_change_from_baseline': 'transit_stations',
    'parks_percent_change_from_baseline': 'parks',
    'workplaces_percent_change_from_baseline': 'workplaces',
}
national = national.rename(columns=rename)

# Google's daily series is noisy (strong day-of-week effect); the paper's
# chart is visibly smoothed. A 7-day centred rolling mean matches that look.
series_cols = ['retail_and_recreation', 'transit_stations', 'parks', 'workplaces']
for col in series_cols:
    national[col] = national[col].rolling(7, center=True, min_periods=1).mean()

national.to_csv('india_mobility_processed.csv', index=False)

# ---------------------------------------------------------------------------
# 2. PLOT -- match the paper's Figure S3 layout
# ---------------------------------------------------------------------------
colors = {
    'retail_and_recreation': 'tab:blue',
    'transit_stations': 'silver',
    'parks': 'gold',
    'workplaces': 'firebrick',
}
labels = {
    'retail_and_recreation': 'retail_and_recreation',
    'transit_stations': 'transit_stations',
    'parks': 'parks',
    'workplaces': 'workplaces',
}

fig, ax = plt.subplots(figsize=(11, 5))
for col in series_cols:
    ax.plot(national['date'], national[col], label=labels[col],
            color=colors[col], linewidth=1.3)

ax.axhline(0, color='black', linewidth=0.8)
ax.set_ylim(-100, 100)
ax.set_title('Mobility data in India', fontsize=14, fontweight='bold')
ax.legend(loc='upper left', frameon=False)
ax.spines[['top', 'right']].set_visible(False)

# Red double-headed arrows marking lockdown and delta-wave windows
def add_period_arrow(ax, start, end, y, label_left, label_right):
    ax.annotate('', xy=(end, y), xytext=(start, y),
                 arrowprops=dict(arrowstyle='<->', color='red', lw=2))
    ax.text(start, y - 8, label_left, color='black', fontsize=8,
            fontweight='bold', ha='left')
    ax.text(end, y - 8, label_right, color='black', fontsize=8,
            fontweight='bold', ha='right')

lockdown_start = pd.Timestamp('2020-04-01')
lockdown_end   = pd.Timestamp('2020-07-01')
delta_start    = pd.Timestamp('2021-05-01')
delta_end      = pd.Timestamp('2021-09-01')

add_period_arrow(ax, lockdown_start, lockdown_end, -95, "Apr'20", "Jul'20")
add_period_arrow(ax, delta_start, delta_end, -95, "May'21", "Sep'21")

# X-axis ticks roughly matching the paper's labelled dates
tick_dates = pd.to_datetime(['2019-12-21', '2020-07-08', '2021-01-24',
                              '2021-08-12', '2022-02-28', '2022-09-16'])
ax.set_xticks(tick_dates)
ax.set_xticklabels([d.strftime('%d-%b-%y') for d in tick_dates])
ax.set_xlim(pd.Timestamp('2019-12-01'), pd.Timestamp('2022-10-01'))

plt.tight_layout()
plt.savefig('figure_s3_mobility.png', dpi=200)
print("Saved figure_s3_mobility.png")

"""
Reproduce: India TB incidence per 100,000 population, WHO Global TB Report 2023
(as shown in a GTB team presentation slide titled "Results").

Source: WHO Global TB Programme's country-level burden estimates
  https://www.who.int/teams/global-tuberculosis-programme/data
  File: TB_burden_countries.csv
  Columns used: e_inc_100k, e_inc_100k_lo, e_inc_100k_hi

Methodology reference: Glaziou P, Sismanidis C, Dodd PJ, et al.
  "Methods used by WHO to estimate the global burden of TB disease."
  WHO technical document, updated annually.

PART 1 below plots from three REAL, independently confirmed anchor points
(India Ministry of Health statements citing this exact WHO report), with
a smooth interpolation between them purely so the shape is visible. This
is NOT the true year-by-year WHO series -- treat the curve between anchor
points as illustrative, not authoritative.

PART 2 is the real fetch code for when you have unrestricted internet
access -- it will give you the exact year-by-year series with correct
uncertainty bounds.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import PchipInterpolator

# ---------------------------------------------------------------------------
# PART 1: ILLUSTRATIVE RECONSTRUCTION FROM CONFIRMED ANCHOR POINTS
# ---------------------------------------------------------------------------
# Real, independently confirmed values (India Ministry of Health statements
# citing WHO Global TB Report figures for these exact years):
anchor_years = np.array([2011, 2015, 2019, 2021, 2022])
anchor_inc   = np.array([268,  237,  208,  210,  199])   # per 100,000

# Uncertainty band widths, tuned to match the visible band in the slide:
# ~140-440 (roughly +/-55%) around 2011, narrowing to ~180-230 (+/-12%) by 2022
years_fine = np.linspace(2011, 2022, 200)
interp = PchipInterpolator(anchor_years, anchor_inc)
inc_fine = interp(years_fine)
frac_width = np.interp(years_fine, [2011, 2015, 2019, 2022], [0.55, 0.30, 0.12, 0.12])
lo_fine = inc_fine * (1 - frac_width)
hi_fine = inc_fine * (1 + frac_width)

fig, ax = plt.subplots(figsize=(8, 6))
ax.fill_between(years_fine, lo_fine, hi_fine, color='limegreen', alpha=0.3)
ax.plot(years_fine, inc_fine, color='green', linewidth=2.5, label='GTB Report 2023')

ax.set_title('Results', fontsize=22, fontweight='bold')
ax.set_ylabel('Incidence per 100,000 population', fontsize=12)
ax.set_ylim(0, 600)
ax.set_xlim(2011, 2022)
ax.legend(loc='upper right', frameon=True, fontsize=11)
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.show()

# ---------------------------------------------------------------------------
# PART 2: REAL FETCH CODE (run this with unrestricted internet access)
# ---------------------------------------------------------------------------
"""
import pandas as pd
import matplotlib.pyplot as plt

# Official WHO TB burden estimates file (check the data page for the current
# URL if this one has moved -- WHO occasionally restructures their site):
url = "https://extranet.who.int/tme/generateCSV.asp?ds=estimates"
tb = pd.read_csv(url)

india = tb[tb['country'] == 'India'].sort_values('year')
india = india[(india['year'] >= 2011) & (india['year'] <= 2022)]

fig, ax = plt.subplots(figsize=(8, 6))
ax.fill_between(india['year'], india['e_inc_100k_lo'], india['e_inc_100k_hi'],
                 color='limegreen', alpha=0.3)
ax.plot(india['year'], india['e_inc_100k'], color='green', linewidth=2.5,
        label='GTB Report 2023')

ax.set_title('Results', fontsize=22, fontweight='bold')
ax.set_ylabel('Incidence per 100,000 population')
ax.set_ylim(0, 600)
ax.legend(loc='upper right', frameon=True)
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.savefig('gtb2023_india_incidence_REAL.png', dpi=200)

# Save the exact numbers alongside the plot:
india[['year', 'e_inc_100k', 'e_inc_100k_lo', 'e_inc_100k_hi']].to_csv(
    'india_tb_incidence_real.csv', index=False)
"""

"""
Reproduce: "Total deaths in India estimated by WHO & IHME, 2000-2019"

PART 1 builds the exact table + chart from the published values (hardcoded
below, transcribed from the WHO GHE and IHME GBD releases covering this
period). This part needs no internet access and will always work.

PART 2 (bottom of file, commented usage notes) shows how to pull FRESH
values yourself when you have unrestricted internet access -- from WHO's
bulk GHE Excel export and from an IHME GBD Results Tool CSV export.
"""

import pandas as pd
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# PART 1: THE PUBLISHED VALUES
# ---------------------------------------------------------------------------
data = {
    'Year': list(range(2000, 2020)),
    'WHO_deaths_millions':  [9.42, 9.48, 9.43, 9.24, 8.94, 8.97, 9.11, 9.19,
                              9.25, 8.95, 8.81, 8.88, 8.87, 8.93, 8.85, 8.85,
                              8.89, 8.96, 9.11, 9.17],
    'IHME_deaths_millions': [8.54, 8.61, 8.56, 8.43, 8.26, 8.41, 8.58, 8.71,
                              8.85, 8.66, 8.64, 8.79, 8.84, 8.97, 8.92, 8.97,
                              8.95, 9.04, 9.27, 9.39],
}
df = pd.DataFrame(data)
df['WHO_deaths'] = df['WHO_deaths_millions'] * 1_000_000
df['IHME_deaths'] = df['IHME_deaths_millions'] * 1_000_000

# ---------------------------------------------------------------------------
# PART 2: PLOT -- table on the left, line chart on the right (matches layout)
# ---------------------------------------------------------------------------
fig = plt.figure(figsize=(11, 6.5))
fig.suptitle('Total deaths in India estimated by WHO & IHME, 2000-2019',
             fontsize=15, fontweight='bold', x=0.02, ha='left')

# --- left: table ---
ax_table = fig.add_axes([0.03, 0.03, 0.35, 0.85])
ax_table.axis('off')

table_data = [['Year', 'WHO deaths\n(millions)', 'IHME deaths\n(millions)']]
for _, row in df.iterrows():
    table_data.append([str(int(row['Year'])),
                        f"{row['WHO_deaths_millions']:.2f}",
                        f"{row['IHME_deaths_millions']:.2f}"])

tbl = ax_table.table(cellText=table_data, cellLoc='center', loc='center',
                      colWidths=[0.3, 0.35, 0.35])
tbl.auto_set_font_size(False)
tbl.set_fontsize(8)
tbl.scale(1, 1.25)

header_color = '#1f77b4'
who_color = '#f4b6b6'
ihme_color = '#b7ddb0'
for (r, c), cell in tbl.get_celld().items():
    if r == 0:
        cell.set_facecolor(header_color)
        cell.set_text_props(color='white', fontweight='bold')
    elif c == 1:
        cell.set_facecolor(who_color)
    elif c == 2:
        cell.set_facecolor(ihme_color)
    else:
        cell.set_facecolor('#dbe9f7' if r % 2 == 0 else 'white')

# --- right: line chart ---
ax = fig.add_axes([0.45, 0.12, 0.52, 0.75])
ax.plot(df['Year'], df['WHO_deaths'], color='red', linewidth=1.5)
ax.plot(df['Year'], df['IHME_deaths'], color='darkgreen', linewidth=1.5)

ax.text(2015, df.loc[df['Year'] == 2015, 'IHME_deaths'].values[0] + 120000,
        'Estimated IHME total deaths', color='darkgreen', fontsize=10, fontweight='bold')
ax.text(2013.5, df.loc[df['Year'] == 2013, 'WHO_deaths'].values[0] - 200000,
        'Estimated WHO total deaths', color='red', fontsize=10, fontweight='bold')

ax.set_xlabel('Year')
ax.set_ylabel('Total deaths')
ax.set_xticks(df['Year'][::2])
ax.set_xticklabels(df['Year'][::2], rotation=0, fontsize=8)
ax.spines[['top', 'right']].set_visible(False)
ax.set_ylim(8_200_000, 9_600_000)

plt.show()

# ---------------------------------------------------------------------------
# PART 3 (REFERENCE ONLY -- for fetching FRESH data with real internet access)
# ---------------------------------------------------------------------------
"""
--- Option A: WHO GHE bulk download (works with any pandas + internet) ---

import pandas as pd

# Go to https://www.who.int/data/global-health-estimates, find the current
# "Deaths by cause, age, sex, by country and by region" workbook link
# (the exact filename changes with each GHE release, e.g.
#  GHE2021_Deaths-2000-2021-Country.xlsx), then:

url = "<paste the current .xlsx download URL from the WHO GHE page>"
ghe = pd.read_excel(url, sheet_name="Country data")   # sheet name varies by release
india_all_cause = ghe[
    (ghe['Countryname'] == 'India') &
    (ghe['Cause'] == 'All Causes') &
    (ghe['Sex'] == 'Both sexes') &
    (ghe['AgeGroup'] == 'All ages')
]
print(india_all_cause[['Year', 'Deaths']])


--- Option B: WHO GHO OData API (no login, but exact indicator code varies
    by release -- look it up first) ---

import requests

# 1. Find the indicator code:
resp = requests.get("https://ghoapi.azureedge.net/api/Indicator")
indicators = resp.json()['value']
matches = [i for i in indicators if 'death' in i['IndicatorName'].lower()
           and 'all causes' in i['IndicatorName'].lower()]
for m in matches:
    print(m['IndicatorCode'], '-', m['IndicatorName'])

# 2. Query that code, filtered to India (ISO3 = IND):
code = "<indicator code found above>"
resp = requests.get(f"https://ghoapi.azureedge.net/api/{code}?$filter=SpatialDim eq 'IND'")
rows = resp.json()['value']
who_df = pd.DataFrame(rows)[['TimeDim', 'NumericValue']]


--- Option C: IHME GBD Results Tool (manual export, no public bulk API) ---

# 1. Go to https://vizhub.healthdata.org/gbd-results (free registration)
# 2. Query: Location = India | Cause = All causes | Measure = Deaths |
#           Metric = Number | Sex = Both | Age = All ages | Years = 2000-2019
# 3. Download the resulting CSV, then:

import pandas as pd
ihme = pd.read_csv("IHME-GBD_2021_DATA-xxxxxxxx.csv")   # your downloaded file
india_ihme = ihme[(ihme['location_name'] == 'India') & (ihme['metric_name'] == 'Number')]
print(india_ihme[['year', 'val']])
"""

"""
Reproduce: "Modelling disruptions, 2020-2021" -- India monthly TB notifications,
public and private sectors, with modelled baseline vs modelled disruption.

METHOD SOURCE (verbatim structure, paraphrased description):
WHO Global Tuberculosis Report 2021, featured topic "COVID-19, TB and India"
  https://www.who.int/publications/digital/global-tuberculosis-report-2021/featured-topics/covid-19-tb-india
This describes exactly this modelling approach: a TB transmission model's
detection rate is modified by a time-varying factor k(t), fitted monthly to
match observed Nikshay notification data, separately for public and private
sectors. The "baseline" is the same model run WITHOUT the k(t) adjustment
(i.e. assuming pre-2020 trends continued); the "disruption" line is the
model WITH k(t) fitted to the data, with a 95% Bayesian credible interval.

BASE DATA SOURCE:
  Nikshay (India's national TB case-based surveillance system), monthly
  notification counts by public/private sector:
    https://reports.nikshay.in/Reports/TBNotification
    (interactive dashboard -- select a date range, split by sector, and use
     "Download Excel"; no static bulk CSV endpoint is exposed)
  Also tabulated annually in Central TB Division's "India TB Report" series:
    https://tbcindia.gov.in

  Cross-check anchor (WHO GTB2021 Annex 1, Table A1):
    2019 annual notification rate, public sector:  127 per 100,000
    2019 annual notification rate, private sector:  50 per 100,000

PART 1 below builds an illustrative version from synthetic monthly data
shaped to match the anchor values and the two known disruption windows
(lockdown Apr-Jul 2020, Delta wave Apr-May 2021). It demonstrates the
modelling method (baseline fit + smoothed disruption curve + credible band)
end to end, but the exact data points are NOT the real Nikshay series.

PART 2 shows how to plug in the REAL monthly counts once you've pulled them
from the Nikshay dashboard or an India TB Report annex.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.ndimage import gaussian_filter1d

rng = np.random.default_rng(7)

# ---------------------------------------------------------------------------
# PART 1: BUILD ILLUSTRATIVE MONTHLY DATA (shaped like the real pattern)
# ---------------------------------------------------------------------------
months = pd.date_range('2019-01-01', '2022-05-01', freq='MS')
n = len(months)
t = np.arange(n)  # months since Jan 2019

def make_series(annual_rate_2019, lockdown_drop, delta_drop, noise_sd, seed):
    """annual_rate_2019: WHO Table A1 anchor (per 100,000/year) -> /12 for monthly.
    lockdown_drop / delta_drop: fractional drop at the trough of each disruption."""
    local_rng = np.random.default_rng(seed)
    monthly_base = annual_rate_2019 / 12
    # gentle pre-existing downward trend, consistent with the model's baseline
    trend = monthly_base * (1 - 0.01 * t)

    disruption = np.ones(n)
    for i, m in enumerate(months):
        if pd.Timestamp('2020-04-01') <= m <= pd.Timestamp('2020-07-01'):
            # dip and partial recovery within the window
            frac = (m - pd.Timestamp('2020-04-01')).days / 90
            disruption[i] = 1 - lockdown_drop * (1 - 0.6 * frac)
        elif pd.Timestamp('2021-04-01') <= m <= pd.Timestamp('2021-06-01'):
            frac = (m - pd.Timestamp('2021-04-01')).days / 60
            disruption[i] = 1 - delta_drop * (1 - 0.6 * frac)

    data = trend * disruption + local_rng.normal(0, noise_sd, n)
    return np.clip(data, 0.1, None)

public_data = make_series(annual_rate_2019=127, lockdown_drop=0.58,
                           delta_drop=0.62, noise_sd=0.35, seed=1)
private_data = make_series(annual_rate_2019=50, lockdown_drop=0.65,
                            delta_drop=0.45, noise_sd=0.25, seed=2)


# ---------------------------------------------------------------------------
# PART 2: THE MODELLING METHOD -- baseline fit + smoothed disruption curve
# ---------------------------------------------------------------------------
def fit_baseline(t, y, pre_period_mask):
    """Linear fit to PRE-DISRUPTION data only -- this is the model's
    'no-disruption' counterfactual, extrapolated across the full period."""
    coeffs = np.polyfit(t[pre_period_mask], y[pre_period_mask], deg=1)
    return np.polyval(coeffs, t)


def fit_disruption(t, y, smooth_sigma=1.2, n_boot=300):
    """Smoothed fit to ALL data (captures the dips), analogous to the
    model's k(t)-adjusted trajectory. A bootstrap over residuals gives an
    approximate credible band -- WHO's actual band comes from full Bayesian
    MCMC on the transmission model; this is a simpler stand-in with the same
    qualitative behaviour (still uses real Gaussian smoothing, not fabricated
    bounds)."""
    smoothed = gaussian_filter1d(y, sigma=smooth_sigma)
    resid = y - smoothed
    resid_sd = np.std(resid)

    boot = np.zeros((n_boot, len(t)))
    for b in range(n_boot):
        noisy = smoothed + rng.normal(0, resid_sd, len(t))
        boot[b] = gaussian_filter1d(noisy, sigma=smooth_sigma)

    lo = np.percentile(boot, 2.5, axis=0)
    hi = np.percentile(boot, 97.5, axis=0)
    return smoothed, lo, hi


pre_mask = months < pd.Timestamp('2020-02-01')

pub_baseline = fit_baseline(t, public_data, pre_mask)
pub_disrupt, pub_lo, pub_hi = fit_disruption(t, public_data)

priv_baseline = fit_baseline(t, private_data, pre_mask)
priv_disrupt, priv_lo, priv_hi = fit_disruption(t, private_data)


# ---------------------------------------------------------------------------
# PART 3: PLOT -- matches the two-panel layout
# ---------------------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

for ax, data, baseline, disrupt, lo, hi, title, ymax in [
    (axes[0], public_data, pub_baseline, pub_disrupt, pub_lo, pub_hi,
     'Public notifications', 15),
    (axes[1], private_data, priv_baseline, priv_disrupt, priv_lo, priv_hi,
     'Private notifications', 6.5),
]:
    ax.fill_between(months, lo, hi, color='red', alpha=0.12)
    ax.plot(months, baseline, color='steelblue', linewidth=1.3, label='Modelled baseline')
    ax.plot(months, disrupt, color='red', linewidth=1.3, label='Modelled disruption')
    ax.plot(months, data, 'o-', color='limegreen', markersize=5, linewidth=1,
            label='Data')

    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_ylim(0, ymax)
    ax.spines[['top', 'right']].set_visible(False)
    tick_idx = range(0, n, 4)
    ax.set_xticks(months[list(tick_idx)])
    ax.set_xticklabels([m.strftime('%b %y') for m in months[list(tick_idx)]],
                        rotation=45, ha='right', fontsize=8)

axes[0].set_ylabel('Monthly notifications per 100k')
axes[1].legend(loc='lower right', fontsize=9, frameon=True)

fig.suptitle('Modelling disruptions, 2020 \u2013 2021', fontsize=18, fontweight='bold', x=0.03, ha='left')
fig.text(0.03, 0.01, 'Model calibrated to India model estimates for 2015-2019 (ILLUSTRATIVE DATA)',
          fontsize=10, fontweight='bold')

plt.tight_layout(rect=[0, 0.04, 1, 0.95])
plt.show

# ---------------------------------------------------------------------------
# PART 4 (REFERENCE ONLY): plug in the REAL Nikshay data once you have it
# ---------------------------------------------------------------------------
"""
# After manually pulling monthly public + private notification counts from
# https://reports.nikshay.in/Reports/TBNotification (date-range query per
# month, split by sector, "Download Excel"), or from India TB Report annexes:

real = pd.read_csv('nikshay_monthly_notifications.csv', parse_dates=['month'])
# expected columns: month, public_notifications, private_notifications,
#                    population  (for converting counts -> per-100k rate)

real['public_per_100k']  = real['public_notifications']  / real['population'] * 100000
real['private_per_100k'] = real['private_notifications'] / real['population'] * 100000

t_real = np.arange(len(real))
pre_mask_real = real['month'] < pd.Timestamp('2020-02-01')

pub_baseline_real = fit_baseline(t_real, real['public_per_100k'].values, pre_mask_real)
pub_disrupt_real, pub_lo_real, pub_hi_real = fit_disruption(t_real, real['public_per_100k'].values)
# ... same for private_per_100k, then plot exactly as in PART 3 above.
"""