# -*- coding: utf-8 -*-
"""sunilnewhivonly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6DHzgKODpTJLL3O-smYotejLSjMnJej
"""

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S -> Ih (HIV) -> Ia (AIDS)
#
# Fitting target: observed Cases = Ih + Ia  (combined active prevalence)
# Initial total infected: Ih0 + Ia0 = 96565
# =============================================================================

def seir_model(y, t, beta_h, kappa, delta_h):
    S, Ih, Ia = y
    N = S + Ih + Ia

    Lambda = 151002   # Annual recruitment into susceptible population
    mu     = 0.0012   # Natural mortality rate

    lambda_h = beta_h * (Ih + Ia) / N   # Force of infection

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa + mu) * Ih   # HIV stage
    dIadt = kappa * Ih  - (delta_h + mu) * Ia  # AIDS stage

    return [dSdt, dIhdt, dIadt]


def neg_log_likelihood(params, t, observed_combined):
    """
    Minimise squared residuals between observed (Ih+Ia) and predicted (Ih+Ia).
    params = [beta_h, kappa, delta_h, Ih0, Ia0]
    Constraint enforced inside: Ih0 + Ia0 <= 96565
    """
    beta_h, kappa, delta_h, Ih0, Ia0 = params

    S0 = 1250345700
    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t, args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]   # Ih + Ia at each time point
        sse = np.sum((observed_combined - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse


# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12 + \
                      (df['Months'].dt.month - df['Months'].dt.month.iloc[0])

t                = df['YearsSinceMin'].values.astype(float)
observed_cases   = df['Cases'].values.astype(float)   # = Ih + Ia combined

# ---------------------------------------------------------------------------
# Parameter estimation
# ---------------------------------------------------------------------------
# Initial guess: [beta_h, kappa, delta_h, Ih0, Ia0]
# Constraint: Ih0 + Ia0 = 96565  (split ~60% HIV, ~40% AIDS as starting guess)
TOTAL_INIT = 96565
initial_guess = [0.46, 0.2456, 0.2508,
                 int(0.60 * TOTAL_INIT),   # Ih0
                 int(0.40 * TOTAL_INIT)]   # Ia0

bounds = [
    (1e-4, 1.0),                   # beta_h
    (1e-4, 1.0),                   # kappa
    (1e-4, 1.0),                   # delta_h
    (1,    TOTAL_INIT - 1),        # Ih0  (must leave room for Ia0 >= 1)
    (1,    TOTAL_INIT - 1),        # Ia0
]

# Soft constraint: penalise if Ih0 + Ia0 deviates from TOTAL_INIT
def objective(params):
    beta_h, kappa, delta_h, Ih0, Ia0 = params
    penalty = 1e6 * (Ih0 + Ia0 - TOTAL_INIT) ** 2  # force sum == 96565
    return neg_log_likelihood(params, t, observed_cases) + penalty

print("Starting parameter estimation (fitting Ih + Ia = observed cases) ...")
result = minimize(
    objective,
    initial_guess,
    bounds=bounds,
    method='L-BFGS-B',
    options={'maxiter': 5000, 'ftol': 1e-12, 'gtol': 1e-10, 'disp': True}
)
params = result.x
beta_h, kappa, delta_h, Ih0_est, Ia0_est = params

# Normalise Ih0/Ia0 exactly to 96565 after optimisation
scale = TOTAL_INIT / (Ih0_est + Ia0_est)
Ih0_est *= scale
Ia0_est *= scale

print(f"\nIh0 + Ia0 (after normalisation): {Ih0_est + Ia0_est:.2f}  (target {TOTAL_INIT})")

# ---------------------------------------------------------------------------
# Final simulation with estimated parameters
# ---------------------------------------------------------------------------
S0 = 1250345700
y0 = [S0, Ih0_est, Ia0_est]

solution = odeint(seir_model, y0, t,
                  args=(beta_h, kappa, delta_h),
                  mxstep=5000)

Ih_fit = solution[:, 1]
Ia_fit = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit   # Combined fitted curve

# ---------------------------------------------------------------------------
# Goodness-of-fit
# ---------------------------------------------------------------------------
ss_res = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1 - ss_res / ss_tot

# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------
plt.figure(figsize=(12, 8))

plt.plot(df['Months'], observed_cases, 'go-',
         label='Observed Cases (HIV + AIDS)', ms=7)
plt.plot(df['Months'], IhIa_fit, 'r-',
         label='Fitted Curve (Ih + Ia)', linewidth=2.5)
plt.plot(df['Months'], Ih_fit, 'b--',
         label='HIV Stage (Ih) — estimated', linewidth=1.8)
plt.plot(df['Months'], Ia_fit, 'm--',
         label='AIDS Stage (Ia) — estimated', linewidth=1.8)

plt.xlabel('Year', fontsize=12, fontweight='bold')
plt.ylabel('Active Infected Cases (Ih + Ia)', fontsize=12, fontweight='bold')
plt.title('HIV-AIDS Model: Combined Ih + Ia Fitted to Observed Cases',
          fontsize=13, fontweight='bold')

plt.gca().xaxis.set_major_formatter(DateFormatter('%Y'))
plt.xticks(rotation=45, fontsize=10, fontweight='bold')
plt.yticks(fontsize=10, fontweight='bold')
plt.legend(fontsize=10, prop={'weight': 'bold'})
plt.tight_layout()
plt.savefig('fitted_curve_IhIa.eps')
plt.savefig('fitted_curve_IhIa.png', dpi=150)
plt.show()

# ---------------------------------------------------------------------------
# Results summary
# ---------------------------------------------------------------------------
print("\n" + "=" * 50)
print("ESTIMATED PARAMETERS")
print("=" * 50)
param_names = ["beta_h", "kappa", "delta_h", "Ih0", "Ia0"]
for name, value in zip(param_names, [beta_h, kappa, delta_h, Ih0_est, Ia0_est]):
    print(f"  {name:<10}: {value:.6f}")

print("\nINITIAL CONDITIONS")
print(f"  S0         : {S0}")
print(f"  Ih0        : {Ih0_est:.2f}   (HIV at t=0)")
print(f"  Ia0        : {Ia0_est:.2f}   (AIDS at t=0)")
print(f"  Ih0 + Ia0  : {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print(f"\nR-squared    : {r_squared:.6f}")

# Basic reproduction number  R0 = beta_h / (kappa + mu)
mu = 0.0012
R0 = beta_h / (kappa + mu)
print(f"R0 (approx)  : {R0:.4f}   [beta_h / (kappa + mu)]")

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S -> Ih (HIV) -> Ia (AIDS)
#
# Fitting target: observed Cases = Ih + Ia  (combined active prevalence)
# Initial total infected: Ih0 + Ia0 = 96565
# =============================================================================

def seir_model(y, t, beta_h, kappa, delta_h):
    S, Ih, Ia = y
    N = S + Ih + Ia

    Lambda = 151002   # Annual recruitment into susceptible population
    mu     = 0.0012   # Natural mortality rate

    lambda_h = beta_h * (Ih + Ia) / N   # Force of infection

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa + mu) * Ih   # HIV stage
    dIadt = kappa * Ih  - (delta_h + mu) * Ia  # AIDS stage

    return [dSdt, dIhdt, dIadt]


def neg_log_likelihood(params, t, observed_combined):
    """
    Minimise squared residuals between observed (Ih+Ia) and predicted (Ih+Ia).
    params = [beta_h, kappa, delta_h, Ih0, Ia0]
    Constraint enforced inside: Ih0 + Ia0 <= 96565
    """
    beta_h, kappa, delta_h, Ih0, Ia0 = params

    S0 = 1250345700
    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t, args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]   # Ih + Ia at each time point
        sse = np.sum((observed_combined - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse


# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12 + \
                      (df['Months'].dt.month - df['Months'].dt.month.iloc[0])

t                = df['YearsSinceMin'].values.astype(float)
observed_cases   = df['Cases'].values.astype(float)   # = Ih + Ia combined

# ---------------------------------------------------------------------------
# Parameter estimation
# ---------------------------------------------------------------------------
# Initial guess: [beta_h, kappa, delta_h, Ih0, Ia0]
# Constraint: Ih0 + Ia0 = 96565  (split ~60% HIV, ~40% AIDS as starting guess)
TOTAL_INIT = 96565
initial_guess = [0.46, 0.2456, 0.2508,
                 int(0.60 * TOTAL_INIT),   # Ih0
                 int(0.40 * TOTAL_INIT)]   # Ia0

bounds = [
    (1e-4, 1.0),                   # beta_h
    (1e-4, 1.0),                   # kappa
    (1e-4, 1.0),                   # delta_h
    (1,    TOTAL_INIT - 1),        # Ih0  (must leave room for Ia0 >= 1)
    (1,    TOTAL_INIT - 1),        # Ia0
]

# Soft constraint: penalise if Ih0 + Ia0 deviates from TOTAL_INIT
def objective(params):
    beta_h, kappa, delta_h, Ih0, Ia0 = params
    penalty = 1e6 * (Ih0 + Ia0 - TOTAL_INIT) ** 2  # force sum == 96565
    return neg_log_likelihood(params, t, observed_cases) + penalty

print("Starting parameter estimation (fitting Ih + Ia = observed cases) ...")
result = minimize(
    objective,
    initial_guess,
    bounds=bounds,
    method='L-BFGS-B',
    options={'maxiter': 5000, 'ftol': 1e-12, 'gtol': 1e-10, 'disp': True}
)
params = result.x
beta_h, kappa, delta_h, Ih0_est, Ia0_est = params

# Normalise Ih0/Ia0 exactly to 96565 after optimisation
scale = TOTAL_INIT / (Ih0_est + Ia0_est)
Ih0_est *= scale
Ia0_est *= scale

print(f"\nIh0 + Ia0 (after normalisation): {Ih0_est + Ia0_est:.2f}  (target {TOTAL_INIT})")

# ---------------------------------------------------------------------------
# Final simulation with estimated parameters
# ---------------------------------------------------------------------------
S0 = 1250345700
y0 = [S0, Ih0_est, Ia0_est]

solution = odeint(seir_model, y0, t,
                  args=(beta_h, kappa, delta_h),
                  mxstep=5000)

Ih_fit = solution[:, 1]
Ia_fit = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit   # Combined fitted curve

# ---------------------------------------------------------------------------
# Goodness-of-fit
# ---------------------------------------------------------------------------
ss_res = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1 - ss_res / ss_tot

# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------
plt.figure(figsize=(12, 8))

plt.plot(df['Months'], observed_cases, 'go-',
         label='Observed Cases (HIV + AIDS)', ms=7)
plt.plot(df['Months'], IhIa_fit, 'r-',
         label='Fitted Curve (Ih + Ia)', linewidth=2.5)
# plt.plot(df['Months'], Ih_fit, 'b--',
#          label='HIV Stage (Ih) — estimated', linewidth=1.8)
# plt.plot(df['Months'], Ia_fit, 'm--',
#          label='AIDS Stage (Ia) — estimated', linewidth=1.8)

plt.xlabel('Year', fontsize=12, fontweight='bold')
plt.ylabel('Active Infected Cases (Ih + Ia)', fontsize=12, fontweight='bold')
plt.title('HIV-AIDS Model: Combined Ih + Ia Fitted to Observed Cases',
          fontsize=13, fontweight='bold')

plt.gca().xaxis.set_major_formatter(DateFormatter('%Y'))
plt.xticks(rotation=45, fontsize=10, fontweight='bold')
plt.yticks(fontsize=10, fontweight='bold')
plt.legend(fontsize=10, prop={'weight': 'bold'})
plt.tight_layout()
plt.savefig('fitted_curve_IhIa.eps')
plt.savefig('fitted_curve_IhIa.png', dpi=150)
plt.show()

# ---------------------------------------------------------------------------
# Results summary
# ---------------------------------------------------------------------------
print("\n" + "=" * 50)
print("ESTIMATED PARAMETERS")
print("=" * 50)
param_names = ["beta_h", "kappa", "delta_h", "Ih0", "Ia0"]
for name, value in zip(param_names, [beta_h, kappa, delta_h, Ih0_est, Ia0_est]):
    print(f"  {name:<10}: {value:.6f}")

print("\nINITIAL CONDITIONS")
print(f"  S0         : {S0}")
print(f"  Ih0        : {Ih0_est:.2f}   (HIV at t=0)")
print(f"  Ia0        : {Ia0_est:.2f}   (AIDS at t=0)")
print(f"  Ih0 + Ia0  : {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print(f"\nR-squared    : {r_squared:.6f}")

# Basic reproduction number  R0 = beta_h / (kappa + mu)
mu = 0.0012
R0 = beta_h / (kappa + mu)
print(f"R0 (approx)  : {R0:.4f}   [beta_h / (kappa + mu)]")

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S -> Ih (HIV) -> Ia (AIDS)
#
# Fitting target: observed Cases = Ih + Ia  (combined active prevalence)
# Initial total infected: Ih0 + Ia0 = 96565
# =============================================================================

def seir_model(y, t, beta_h, kappa, delta_h):
    S, Ih, Ia = y
    N = S + Ih + Ia

    Lambda = 151002   # Annual recruitment into susceptible population
    mu     = 0.0012   # Natural mortality rate

    lambda_h = beta_h * (Ih + Ia) / N   # Force of infection

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa + mu) * Ih   # HIV stage
    dIadt = kappa * Ih  - (delta_h + mu) * Ia  # AIDS stage

    return [dSdt, dIhdt, dIadt]


def neg_log_likelihood(params, t, observed_combined):
    """
    Minimise squared residuals between observed (Ih+Ia) and predicted (Ih+Ia).
    params = [beta_h, kappa, delta_h, Ih0, Ia0]
    Constraint enforced inside: Ih0 + Ia0 <= 96565
    """
    beta_h, kappa, delta_h, Ih0, Ia0 = params

    S0 = 1250345700
    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t, args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]   # Ih + Ia at each time point
        sse = np.sum((observed_combined - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse


# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12 + \
                      (df['Months'].dt.month - df['Months'].dt.month.iloc[0])

t                = df['YearsSinceMin'].values.astype(float)
observed_cases   = df['Cases'].values.astype(float)   # = Ih + Ia combined

# ---------------------------------------------------------------------------
# Parameter estimation
# ---------------------------------------------------------------------------
# Initial guess: [beta_h, kappa, delta_h, Ih0, Ia0]
# Constraint: Ih0 + Ia0 = 96565  (split ~60% HIV, ~40% AIDS as starting guess)
TOTAL_INIT = 96565
initial_guess = [0.946, 0.2456, 0.2508,
                 int(0.60 * TOTAL_INIT),   # Ih0
                 int(0.40 * TOTAL_INIT)]   # Ia0

bounds = [
    (1e-4, 1.0),                   # beta_h
    (1e-4, 1.0),                   # kappa
    (1e-4, 1.0),                   # delta_h
    (1,    TOTAL_INIT - 1),        # Ih0  (must leave room for Ia0 >= 1)
    (1,    TOTAL_INIT - 1),        # Ia0
]

# Soft constraint: penalise if Ih0 + Ia0 deviates from TOTAL_INIT
def objective(params):
    beta_h, kappa, delta_h, Ih0, Ia0 = params
    penalty = 1e6 * (Ih0 + Ia0 - TOTAL_INIT) ** 2  # force sum == 96565
    return neg_log_likelihood(params, t, observed_cases) + penalty

print("Starting parameter estimation (fitting Ih + Ia = observed cases) ...")
result = minimize(
    objective,
    initial_guess,
    bounds=bounds,
    method='L-BFGS-B',
    options={'maxiter': 5000, 'ftol': 1e-12, 'gtol': 1e-10, 'disp': True}
)
params = result.x
beta_h, kappa, delta_h, Ih0_est, Ia0_est = params

# Normalise Ih0/Ia0 exactly to 96565 after optimisation
scale = TOTAL_INIT / (Ih0_est + Ia0_est)
Ih0_est *= scale
Ia0_est *= scale

print(f"\nIh0 + Ia0 (after normalisation): {Ih0_est + Ia0_est:.2f}  (target {TOTAL_INIT})")

# ---------------------------------------------------------------------------
# Final simulation with estimated parameters
# ---------------------------------------------------------------------------
S0 = 1250345700
y0 = [S0, Ih0_est, Ia0_est]

solution = odeint(seir_model, y0, t,
                  args=(beta_h, kappa, delta_h),
                  mxstep=5000)

Ih_fit = solution[:, 1]
Ia_fit = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit   # Combined fitted curve

# ---------------------------------------------------------------------------
# Goodness-of-fit
# ---------------------------------------------------------------------------
ss_res = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1 - ss_res / ss_tot

# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------
plt.figure(figsize=(12, 8))

plt.plot(df['Months'], observed_cases, 'go-',
         label='Observed Cases (HIV + AIDS)', ms=7)
plt.plot(df['Months'], IhIa_fit, 'r-',
         label='Fitted Curve (Ih + Ia)', linewidth=2.5)
# plt.plot(df['Months'], Ih_fit, 'b--',
#          label='HIV Stage (Ih) — estimated', linewidth=1.8)
# plt.plot(df['Months'], Ia_fit, 'm--',
#          label='AIDS Stage (Ia) — estimated', linewidth=1.8)

plt.xlabel('Year', fontsize=12, fontweight='bold')
plt.ylabel('Active Infected Cases (Ih + Ia)', fontsize=12, fontweight='bold')
plt.title('HIV-AIDS Model: Combined Ih + Ia Fitted to Observed Cases',
          fontsize=13, fontweight='bold')

plt.gca().xaxis.set_major_formatter(DateFormatter('%Y'))
plt.xticks(rotation=45, fontsize=10, fontweight='bold')
plt.yticks(fontsize=10, fontweight='bold')
plt.legend(fontsize=10, prop={'weight': 'bold'})
plt.tight_layout()
plt.savefig('fitted_curve_IhIa.eps')
plt.savefig('fitted_curve_IhIa.png', dpi=150)
plt.show()

# ---------------------------------------------------------------------------
# Results summary
# ---------------------------------------------------------------------------
print("\n" + "=" * 50)
print("ESTIMATED PARAMETERS")
print("=" * 50)
param_names = ["beta_h", "kappa", "delta_h", "Ih0", "Ia0"]
for name, value in zip(param_names, [beta_h, kappa, delta_h, Ih0_est, Ia0_est]):
    print(f"  {name:<10}: {value:.6f}")

print("\nINITIAL CONDITIONS")
print(f"  S0         : {S0}")
print(f"  Ih0        : {Ih0_est:.2f}   (HIV at t=0)")
print(f"  Ia0        : {Ia0_est:.2f}   (AIDS at t=0)")
print(f"  Ih0 + Ia0  : {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print(f"\nR-squared    : {r_squared:.6f}")

# Basic reproduction number  R0 = beta_h / (kappa + mu)
mu = 0.0012
R0 = beta_h / (kappa + mu)
print(f"R0 (approx)  : {R0:.4f}   [beta_h / (kappa + mu)]")

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S -> Ih (HIV) -> Ia (AIDS)
#
# Fitting target : observed Cases = Ih + Ia  (combined active prevalence)
# Initial total  : Ih0 + Ia0 = 96565
# Constraint     : R0 = beta_h / (kappa + mu)  >  1   (endemic disease)
# =============================================================================

Lambda = 151002
mu     = 0.0012


def seir_model(y, t, beta_h, kappa, delta_h):
    S, Ih, Ia = y
    N = S + Ih + Ia

    lambda_h = beta_h * (Ih + Ia) / N

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa + mu) * Ih   # HIV stage
    dIadt = kappa * Ih  - (delta_h + mu) * Ia  # AIDS stage

    return [dSdt, dIhdt, dIadt]


def objective(params, t, observed):
    beta_h, kappa, delta_h, Ih0, Ia0 = params

    # --- Penalty 1: Ih0 + Ia0 must equal 96565 ---
    TOTAL_INIT = 96565
    penalty_init = 1e6 * (Ih0 + Ia0 - TOTAL_INIT) ** 2

    # --- Penalty 2: R0 must be > 1 (strictly) ---
    R0 = beta_h / (kappa + mu)
    penalty_R0 = 1e8 * max(0.0, 1.01 - R0) ** 2   # zero when R0 >= 1.01

    S0 = 1250345700
    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t,
                     args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]          # Ih + Ia
        sse = np.sum((observed - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse + penalty_init + penalty_R0


# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12

t              = df['YearsSinceMin'].values.astype(float)
observed_cases = df['Cases'].values.astype(float)   # Ih + Ia per year

TOTAL_INIT = 96565

# ---------------------------------------------------------------------------
# Parameter estimation
# ---------------------------------------------------------------------------
# Initial guess designed so that R0 = beta_h / (kappa + mu) > 1
# e.g. beta_h=0.5, kappa=0.20  =>  R0 = 0.5 / 0.2012 ≈ 2.49  > 1
initial_guess = [0.50, 0.20, 0.25,
                 int(0.60 * TOTAL_INIT),   # Ih0
                 int(0.40 * TOTAL_INIT)]   # Ia0

bounds = [
    (1e-3, 1.0),                   # beta_h
    (1e-3, 0.999),                 # kappa   (kept < 1 to allow R0 > 1)
    (1e-3, 1.0),                   # delta_h
    (1,    TOTAL_INIT - 1),        # Ih0
    (1,    TOTAL_INIT - 1),        # Ia0
]

print("Starting parameter estimation ...")
print(f"Constraint: R0 = beta_h / (kappa + mu) > 1\n")

result = minimize(
    objective,
    initial_guess,
    args=(t, observed_cases),
    bounds=bounds,
    method='L-BFGS-B',
    options={'maxiter': 10000, 'ftol': 1e-14, 'gtol': 1e-10}
)

params = result.x
beta_h, kappa, delta_h, Ih0_est, Ia0_est = params

# Normalise Ih0 / Ia0 exactly to TOTAL_INIT after optimisation
scale   = TOTAL_INIT / (Ih0_est + Ia0_est)
Ih0_est *= scale
Ia0_est *= scale

# ---------------------------------------------------------------------------
# Final simulation
# ---------------------------------------------------------------------------
S0 = 1250345700
y0 = [S0, Ih0_est, Ia0_est]

solution = odeint(seir_model, y0, t,
                  args=(beta_h, kappa, delta_h),
                  mxstep=5000)

Ih_fit   = solution[:, 1]
Ia_fit   = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit

# ---------------------------------------------------------------------------
# Goodness-of-fit
# ---------------------------------------------------------------------------
ss_res    = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot    = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1 - ss_res / ss_tot

R0 = beta_h / (kappa + mu)

# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------
plt.figure(figsize=(12, 8))

plt.plot(df['Months'], observed_cases, 'go-',
         label='Observed Cases (HIV + AIDS)', ms=7)
plt.plot(df['Months'], IhIa_fit, 'r-',
         label='Fitted Curve (Ih + Ia)', linewidth=2.5)
plt.plot(df['Months'], Ih_fit, 'b--',
         label='HIV Stage Ih — estimated', linewidth=1.8)
plt.plot(df['Months'], Ia_fit, 'm--',
         label='AIDS Stage Ia — estimated', linewidth=1.8)

plt.xlabel('Year', fontsize=12, fontweight='bold')
plt.ylabel('Active Infected Cases (Ih + Ia)', fontsize=12, fontweight='bold')
plt.title(f'HIV-AIDS Model Fit  |  R\u2080 = {R0:.4f} > 1',
          fontsize=13, fontweight='bold')

plt.gca().xaxis.set_major_formatter(DateFormatter('%Y'))
plt.xticks(rotation=45, fontsize=10, fontweight='bold')
plt.yticks(fontsize=10, fontweight='bold')
plt.legend(fontsize=10, prop={'weight': 'bold'})
plt.tight_layout()
plt.savefig('fitted_curve_IhIa_R0gt1.eps')
plt.savefig('fitted_curve_IhIa_R0gt1.png', dpi=150)
plt.show()

# ---------------------------------------------------------------------------
# Results summary
# ---------------------------------------------------------------------------
print("=" * 55)
print("ESTIMATED PARAMETERS")
print("=" * 55)
for name, val in zip(["beta_h", "kappa", "delta_h", "Ih0", "Ia0"],
                     [beta_h, kappa, delta_h, Ih0_est, Ia0_est]):
    print(f"  {name:<10}: {val:.6f}")

print("\nINITIAL CONDITIONS")
print(f"  S0         : {S0}")
print(f"  Ih0        : {Ih0_est:.2f}   (HIV at t = 0)")
print(f"  Ia0        : {Ia0_est:.2f}   (AIDS at t = 0)")
print(f"  Ih0 + Ia0  : {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print(f"\nGOODNESS-OF-FIT")
print(f"  R-squared  : {r_squared:.6f}")

print(f"\nEPIDEMIOLOGICAL THRESHOLD")
print(f"  R0         : {R0:.4f}   [beta_h / (kappa + mu)]")
print(f"  R0 > 1     : {'YES ✓  (endemic / spreading)' if R0 > 1 else 'NO ✗'}")

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import differential_evolution, minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S → Ih (HIV Stage) → Ia (AIDS Stage)
#
# Fitting target  : observed Cases = Ih + Ia  (combined active prevalence)
# Initial total   : Ih0 + Ia0 = 96565  (enforced via fraction parameterisation)
# R0 constraint   : R0 = beta_h / (kappa + mu) > 1  (enforced by reparameterisation)
#
# Reparameterisation trick:
#   beta_h = (kappa + mu) * (1 + eps),  eps > 0
#   => R0 = 1 + eps  which is ALWAYS > 1 by construction
# =============================================================================

# ── Fixed demographic parameters ─────────────────────────────────────────────
Lambda = 151002   # annual recruitment into susceptible population
mu     = 0.0012   # natural background mortality rate
TOTAL_INIT = 96565   # total infected at baseline year (Ih0 + Ia0)
S0         = 1250345700

# ── ODE system ───────────────────────────────────────────────────────────────
def seir_model(y, t, beta_h, kappa, delta_h):
    """
    Compartments:
      S  – Susceptible
      Ih – HIV-positive (not yet AIDS)
      Ia – AIDS stage
    """
    S, Ih, Ia = y
    N = S + Ih + Ia

    lambda_h = beta_h * (Ih + Ia) / N        # force of infection

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa  + mu) * Ih
    dIadt = kappa  * Ih  - (delta_h + mu) * Ia

    return [dSdt, dIhdt, dIadt]


# ── Objective function (reparameterised) ─────────────────────────────────────
def objective(params, t, observed):
    """
    Free parameters: [eps, kappa, delta_h, frac]
      eps     : R0 excess above 1  (R0 = 1 + eps,  eps > 0)
      kappa   : progression rate HIV → AIDS
      delta_h : AIDS-related mortality / removal rate
      frac    : fraction of TOTAL_INIT assigned to Ih0  (rest goes to Ia0)
    """
    eps, kappa, delta_h, frac = params

    # Recover beta_h so that R0 = 1 + eps  (always > 1)
    beta_h = (kappa + mu) * (1.0 + eps)

    Ih0 = frac         * TOTAL_INIT
    Ia0 = (1.0 - frac) * TOTAL_INIT

    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t,
                     args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]          # Ih + Ia at each time point
        sse = np.sum((observed - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse


# ── Load data ─────────────────────────────────────────────────────────────────
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12

t              = df['YearsSinceMin'].values.astype(float)
observed_cases = df['Cases'].values.astype(float)

# ── Step 1: Global search with Differential Evolution ────────────────────────
# bounds for [eps, kappa, delta_h, frac]
bounds_de = [
    (0.01, 5.0),    # eps    → R0 = 1+eps ∈ [1.01, 6.0]
    (1e-4, 0.5),    # kappa
    (1e-4, 0.5),    # delta_h
    (0.01, 0.99),   # frac   (Ih0 = frac * 96565)
]

print("=" * 60)
print("Step 1: Global search via Differential Evolution ...")
print("=" * 60)
res_de = differential_evolution(
    objective,
    bounds_de,
    args=(t, observed_cases),
    seed=42,
    maxiter=2000,
    tol=1e-12,
    popsize=20,
    mutation=(0.5, 1.5),
    recombination=0.9,
    workers=1,
    disp=False          # set True to watch DE progress
)
print(f"DE complete.  Best SSE = {res_de.fun:.4f}")

# ── Step 2: Local refinement with L-BFGS-B ───────────────────────────────────
print("\nStep 2: Local refinement via L-BFGS-B ...")
res = minimize(
    objective,
    res_de.x,
    args=(t, observed_cases),
    bounds=bounds_de,
    method='L-BFGS-B',
    options={'maxiter': 10000, 'ftol': 1e-15, 'gtol': 1e-12}
)

# ── Recover final parameters ─────────────────────────────────────────────────
eps_est, kappa_est, delta_h_est, frac_est = res.x

beta_h_est = (kappa_est + mu) * (1.0 + eps_est)   # guaranteed R0 > 1
Ih0_est    = frac_est         * TOTAL_INIT
Ia0_est    = (1.0 - frac_est) * TOTAL_INIT
R0         = beta_h_est / (kappa_est + mu)         # = 1 + eps_est

# ── Final ODE simulation ──────────────────────────────────────────────────────
y0       = [S0, Ih0_est, Ia0_est]
solution = odeint(seir_model, y0, t,
                  args=(beta_h_est, kappa_est, delta_h_est),
                  mxstep=5000)

Ih_fit   = solution[:, 1]
Ia_fit   = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit

# ── Goodness-of-fit ───────────────────────────────────────────────────────────
ss_res    = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot    = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1.0 - ss_res / ss_tot

# ── Plot ──────────────────────────────────────────────────────────────────────
plt.figure(figsize=(12, 8))

plt.plot(df['Months'], observed_cases, 'go-',
         label='Observed Cases (HIV + AIDS)', ms=7)
plt.plot(df['Months'], IhIa_fit, 'r-',
         label='Fitted Curve  (Ih + Ia)', linewidth=2.5)
# plt.plot(df['Months'], Ih_fit,   'b--',
#          label='HIV Stage  Ih  (estimated)', linewidth=1.8)
# plt.plot(df['Months'], Ia_fit,   'm--',
#          label='AIDS Stage  Ia  (estimated)', linewidth=1.8)

plt.xlabel('Year',                fontsize=12, fontweight='bold')
plt.ylabel('Active Cases (Ih + Ia)', fontsize=12, fontweight='bold')
plt.title(f'HIV-AIDS Model Fit  |  R\u2080 = {R0:.4f} > 1  |  R² = {r_squared:.6f}',
          fontsize=13, fontweight='bold')

plt.gca().xaxis.set_major_formatter(DateFormatter('%Y'))
plt.xticks(rotation=45, fontsize=10, fontweight='bold')
plt.yticks(fontsize=10, fontweight='bold')
plt.legend(fontsize=10, prop={'weight': 'bold'})
plt.tight_layout()
plt.savefig('fitted_curve_R0gt1.eps')
plt.savefig('fitted_curve_R0gt1.png', dpi=150)
plt.show()

# ── Results summary ───────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("ESTIMATED PARAMETERS")
print("=" * 60)
print(f"  beta_h     = {beta_h_est:.8f}   (transmission rate)")
print(f"  kappa      = {kappa_est:.8f}   (HIV → AIDS progression rate)")
print(f"  delta_h    = {delta_h_est:.8f}   (AIDS removal/mortality rate)")

print("\nINITIAL CONDITIONS")
print(f"  S0         = {S0}")
print(f"  Ih0        = {Ih0_est:.4f}   (HIV-positive at t = 0)")
print(f"  Ia0        = {Ia0_est:.4f}   (AIDS patients at t = 0)")
print(f"  Ih0 + Ia0  = {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print("\nGOODNESS-OF-FIT")
print(f"  R-squared  = {r_squared:.8f}")

print("\nEPIDEMIOLOGICAL THRESHOLD")
print(f"  R0         = beta_h / (kappa + mu)")
print(f"             = {beta_h_est:.8f} / ({kappa_est:.8f} + {mu})")
print(f"             = {R0:.6f}")
print(f"  R0 > 1     : {'✓  YES — disease is endemic / spreading' if R0 > 1 else '✗  NO'}")

print("\nOBSERVED vs PREDICTED")
print(f"  {'Year':<6}  {'Observed':>10}  {'Predicted':>12}  {'Residual':>10}")
print("  " + "-" * 44)
years = df['Months'].dt.year.values
for yr, obs, pred in zip(years, observed_cases, IhIa_fit):
    print(f"  {yr:<6}  {obs:>10.0f}  {pred:>12.2f}  {obs - pred:>10.2f}")

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import differential_evolution, minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S → Ih (HIV Stage) → Ia (AIDS Stage)
#
# Fitting target  : observed Cases = Ih + Ia  (combined active prevalence)
# Initial total   : Ih0 + Ia0 = 96565  (enforced via fraction parameterisation)
# R0 constraint   : R0 = beta_h / (kappa + mu) > 1  (enforced by reparameterisation)
#
# Reparameterisation trick:
#   beta_h = (kappa + mu) * (1 + eps),  eps > 0
#   => R0 = 1 + eps  which is ALWAYS > 1 by construction
# =============================================================================

# ── Fixed demographic parameters ─────────────────────────────────────────────
Lambda = 151002   # annual recruitment into susceptible population
mu     = 0.0012   # natural background mortality rate
TOTAL_INIT = 96565   # total infected at baseline year (Ih0 + Ia0)
S0         = 1250345700

# ── ODE system ───────────────────────────────────────────────────────────────
def seir_model(y, t, beta_h, kappa, delta_h):
    """
    Compartments:
      S  – Susceptible
      Ih – HIV-positive (not yet AIDS)
      Ia – AIDS stage
    """
    S, Ih, Ia = y
    N = S + Ih + Ia

    lambda_h = beta_h * (Ih + Ia) / N        # force of infection

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa  + mu) * Ih
    dIadt = kappa  * Ih  - (delta_h + mu) * Ia

    return [dSdt, dIhdt, dIadt]


# ── Objective function (reparameterised) ─────────────────────────────────────
def objective(params, t, observed):
    """
    Free parameters: [eps, kappa, delta_h, frac]
      eps     : R0 excess above 1  (R0 = 1 + eps,  eps > 0)
      kappa   : progression rate HIV → AIDS
      delta_h : AIDS-related mortality / removal rate
      frac    : fraction of TOTAL_INIT assigned to Ih0  (rest goes to Ia0)
    """
    eps, kappa, delta_h, frac = params

    # Recover beta_h so that R0 = 1 + eps  (always > 1)
    beta_h = (kappa + mu) * (1.0 + eps)

    Ih0 = frac         * TOTAL_INIT
    Ia0 = (1.0 - frac) * TOTAL_INIT

    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t,
                     args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]          # Ih + Ia at each time point
        sse = np.sum((observed - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse


# ── Load data ─────────────────────────────────────────────────────────────────
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12

t              = df['YearsSinceMin'].values.astype(float)
observed_cases = df['Cases'].values.astype(float)

# ── Step 1: Global search with Differential Evolution ────────────────────────
# bounds for [eps, kappa, delta_h, frac]
bounds_de = [
    (0.01, 5.0),    # eps    → R0 = 1+eps ∈ [1.01, 6.0]
    (1e-4, 0.5),    # kappa
    (1e-4, 0.5),    # delta_h
    (0.01, 0.99),   # frac   (Ih0 = frac * 96565)
]

print("=" * 60)
print("Step 1: Global search via Differential Evolution ...")
print("=" * 60)
res_de = differential_evolution(
    objective,
    bounds_de,
    args=(t, observed_cases),
    seed=42,
    maxiter=2000,
    tol=1e-12,
    popsize=20,
    mutation=(0.5, 1.5),
    recombination=0.9,
    workers=1,
    disp=False          # set True to watch DE progress
)
print(f"DE complete.  Best SSE = {res_de.fun:.4f}")

# ── Step 2: Local refinement with L-BFGS-B ───────────────────────────────────
print("\nStep 2: Local refinement via L-BFGS-B ...")
res = minimize(
    objective,
    res_de.x,
    args=(t, observed_cases),
    bounds=bounds_de,
    method='L-BFGS-B',
    options={'maxiter': 10000, 'ftol': 1e-15, 'gtol': 1e-12}
)

# ── Recover final parameters ─────────────────────────────────────────────────
eps_est, kappa_est, delta_h_est, frac_est = res.x

beta_h_est = (kappa_est + mu) * (1.0 + eps_est)   # guaranteed R0 > 1
Ih0_est    = frac_est         * TOTAL_INIT
Ia0_est    = (1.0 - frac_est) * TOTAL_INIT
R0         = beta_h_est / (kappa_est + mu)         # = 1 + eps_est

# ── Final ODE simulation ──────────────────────────────────────────────────────
y0       = [S0, Ih0_est, Ia0_est]
solution = odeint(seir_model, y0, t,
                  args=(beta_h_est, kappa_est, delta_h_est),
                  mxstep=5000)

Ih_fit   = solution[:, 1]
Ia_fit   = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit

# ── Goodness-of-fit ───────────────────────────────────────────────────────────
ss_res    = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot    = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1.0 - ss_res / ss_tot

# ── Plot ──────────────────────────────────────────────────────────────────────
plt.figure(figsize=(12, 8))

plt.plot(df['Months'], observed_cases, 'go-',
         label='Observed Cases (HIV + AIDS)', ms=7)
plt.plot(df['Months'], IhIa_fit, 'r-',
         label='Fitted Curve  (Ih + Ia)', linewidth=2.5)
# plt.plot(df['Months'], Ih_fit,   'b--',
#          label='HIV Stage  Ih  (estimated)', linewidth=1.8)
# plt.plot(df['Months'], Ia_fit,   'm--',
#          label='AIDS Stage  Ia  (estimated)', linewidth=1.8)

plt.xlabel('Year',                fontsize=12, fontweight='bold')
plt.ylabel('Active Cases (Ih + Ia)', fontsize=12, fontweight='bold')
plt.title(f'HIV-AIDS Model Fit  |  R\u2080 = {R0:.4f} > 1  |  R² = {r_squared:.6f}',
          fontsize=13, fontweight='bold')

plt.gca().xaxis.set_major_formatter(DateFormatter('%Y'))
plt.xticks(rotation=45, fontsize=10, fontweight='bold')
plt.yticks(fontsize=10, fontweight='bold')
plt.legend(fontsize=10, prop={'weight': 'bold'})
plt.tight_layout()
plt.savefig('fitted_curve_R0gt1.eps')
plt.savefig('fitted_curve_R0gt1.png', dpi=150)
plt.show()

# ── Results summary ───────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("ESTIMATED PARAMETERS")
print("=" * 60)
print(f"  beta_h     = {beta_h_est:.8f}   (transmission rate)")
print(f"  kappa      = {kappa_est:.8f}   (HIV → AIDS progression rate)")
print(f"  delta_h    = {delta_h_est:.8f}   (AIDS removal/mortality rate)")

print("\nINITIAL CONDITIONS")
print(f"  S0         = {S0}")
print(f"  Ih0        = {Ih0_est:.4f}   (HIV-positive at t = 0)")
print(f"  Ia0        = {Ia0_est:.4f}   (AIDS patients at t = 0)")
print(f"  Ih0 + Ia0  = {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print("\nGOODNESS-OF-FIT")
print(f"  R-squared  = {r_squared:.8f}")

print("\nEPIDEMIOLOGICAL THRESHOLD")
print(f"  R0         = beta_h / (kappa + mu)")
print(f"             = {beta_h_est:.8f} / ({kappa_est:.8f} + {mu})")
print(f"             = {R0:.6f}")
print(f"  R0 > 1     : {'✓  YES — disease is endemic / spreading' if R0 > 1 else '✗  NO'}")

print("\nOBSERVED vs PREDICTED")
print(f"  {'Year':<6}  {'Observed':>10}  {'Predicted':>12}  {'Residual':>10}")
print("  " + "-" * 44)
years = df['Months'].dt.year.values
for yr, obs, pred in zip(years, observed_cases, IhIa_fit):
    print(f"  {yr:<6}  {obs:>10.0f}  {pred:>12.2f}  {obs - pred:>10.2f}")

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import differential_evolution, minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S → Ih (HIV Stage) → Ia (AIDS Stage)
#
# Fitting target  : observed Cases = Ih + Ia  (combined active prevalence)
# Initial total   : Ih0 + Ia0 = 96565  (enforced via fraction parameterisation)
# R0 constraint   : R0 = beta_h / (kappa + mu) > 1  (enforced by reparameterisation)
#
# Reparameterisation trick:
#   beta_h = (kappa + mu) * (1 + eps),  eps > 0
#   => R0 = 1 + eps  which is ALWAYS > 1 by construction
# =============================================================================

# ── Fixed demographic parameters ─────────────────────────────────────────────
Lambda = 151002   # annual recruitment into susceptible population
mu     = 0.0012   # natural background mortality rate
TOTAL_INIT = 96565   # total infected at baseline year (Ih0 + Ia0)
S0         = 1250345700

# ── ODE system ───────────────────────────────────────────────────────────────
def seir_model(y, t, beta_h, kappa, delta_h):
    """
    Compartments:
      S  – Susceptible
      Ih – HIV-positive (not yet AIDS)
      Ia – AIDS stage
    """
    S, Ih, Ia = y
    N = S + Ih + Ia

    lambda_h = beta_h * (Ih + Ia) / N        # force of infection

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa  + mu) * Ih
    dIadt = kappa  * Ih  - (delta_h + mu) * Ia

    return [dSdt, dIhdt, dIadt]


# ── Objective function (reparameterised) ─────────────────────────────────────
def objective(params, t, observed):
    """
    Free parameters: [eps, kappa, delta_h, frac]
      eps     : R0 excess above 1  (R0 = 1 + eps,  eps > 0)
      kappa   : progression rate HIV → AIDS
      delta_h : AIDS-related mortality / removal rate
      frac    : fraction of TOTAL_INIT assigned to Ih0  (rest goes to Ia0)
    """
    eps, kappa, delta_h, frac = params

    # Recover beta_h so that R0 = 1 + eps  (always > 1)
    beta_h = (kappa + mu) * (1.0 + eps)

    Ih0 = frac         * TOTAL_INIT
    Ia0 = (1.0 - frac) * TOTAL_INIT

    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t,
                     args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]          # Ih + Ia at each time point
        sse = np.sum((observed - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse


# ── Load data ─────────────────────────────────────────────────────────────────
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12

t              = df['YearsSinceMin'].values.astype(float)
observed_cases = df['Cases'].values.astype(float)

# ── Step 1: Global search with Differential Evolution ────────────────────────
# bounds for [eps, kappa, delta_h, frac]
bounds_de = [
    (0.01, 5.0),    # eps    → R0 = 1+eps ∈ [1.01, 6.0]
    (1e-4, 0.5),    # kappa
    (1e-4, 0.5),    # delta_h
    (0.01, 0.99),   # frac   (Ih0 = frac * 96565)
]

print("=" * 60)
print("Step 1: Global search via Differential Evolution ...")
print("=" * 60)
res_de = differential_evolution(
    objective,
    bounds_de,
    args=(t, observed_cases),
    seed=42,
    maxiter=2000,
    tol=1e-12,
    popsize=20,
    mutation=(0.5, 1.5),
    recombination=0.9,
    workers=1,
    disp=False          # set True to watch DE progress
)
print(f"DE complete.  Best SSE = {res_de.fun:.4f}")

# ── Step 2: Local refinement with L-BFGS-B ───────────────────────────────────
print("\nStep 2: Local refinement via L-BFGS-B ...")
res = minimize(
    objective,
    res_de.x,
    args=(t, observed_cases),
    bounds=bounds_de,
    method='L-BFGS-B',
    options={'maxiter': 10000, 'ftol': 1e-15, 'gtol': 1e-12}
)

# ── Recover final parameters ─────────────────────────────────────────────────
eps_est, kappa_est, delta_h_est, frac_est = res.x

beta_h_est = (kappa_est + mu) * (1.0 + eps_est)   # guaranteed R0 > 1
Ih0_est    = frac_est         * TOTAL_INIT
Ia0_est    = (1.0 - frac_est) * TOTAL_INIT
R0         = beta_h_est / (kappa_est + mu)         # = 1 + eps_est

# ── Final ODE simulation ──────────────────────────────────────────────────────
y0       = [S0, Ih0_est, Ia0_est]
solution = odeint(seir_model, y0, t,
                  args=(beta_h_est, kappa_est, delta_h_est),
                  mxstep=5000)

Ih_fit   = solution[:, 1]
Ia_fit   = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit

# ── Goodness-of-fit ───────────────────────────────────────────────────────────
ss_res    = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot    = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1.0 - ss_res / ss_tot

# ── RMSE and 95% Confidence Interval ─────────────────────────────────────────
rmse = np.sqrt(np.mean((observed_cases - IhIa_fit) ** 2))

# Approximate 95% CI based on RMSE
ci = 1.96 * rmse

lower_ci = IhIa_fit - ci
upper_ci = IhIa_fit + ci

# Avoid negative values in the lower confidence limit
lower_ci = np.maximum(lower_ci, 0)

# Final fitted active cases
final_fitted_cases = IhIa_fit[-1]


# ── Plot ──────────────────────────────────────────────────────────────────────
plt.figure(figsize=(10, 6))

plt.plot(
    df['Months'],
    observed_cases,
    'go',
    label='Observed Cases',
    ms=7
)

plt.plot(
    df['Months'],
    IhIa_fit,
    'r-',
    label='Fitted Curve',
    linewidth=2.5
)

# 95% Confidence Interval
plt.fill_between(
    df['Months'],
    lower_ci,
    upper_ci,
    color='gray',
    alpha=0.35,
    label='95% CI'
)

plt.xlabel(
    'Year',
    fontsize=12,
    fontweight='bold'
)

plt.ylabel(
    'Active Cases ($I_H + I_A$)',
    fontsize=12,
    fontweight='bold'
)

# ── X-axis ────────────────────────────────────────────────────────────────────
ax = plt.gca()

# Set x-axis limits from 2010 to 2024
ax.set_xlim(
    pd.Timestamp('2009-06-06'),
    pd.Timestamp('2023-06-06')
)

# Show every year from 2010 to 2024
tick_dates = pd.date_range(
    start='2010-01-01',
    end='2023-01-01',
    freq='YS'
)

ax.set_xticks(tick_dates)

# Display labels as 2010, 2011, ..., 2023, 2024
ax.set_xticklabels(
    [date.strftime('%Y') for date in tick_dates],
    rotation=45,
    fontsize=10,
    fontweight='bold'
)

# ── Y-axis: automatically extend according to data and CI ─────────────────────
# ── Y-axis: start near the observed minimum and extend above maximum ──────────
from matplotlib.ticker import MultipleLocator

# Find the minimum and maximum values including the 95% CI
y_min = min(
    np.min(observed_cases),
    np.min(IhIa_fit),
    np.min(lower_ci)
)

y_max = max(
    np.max(observed_cases),
    np.max(IhIa_fit),
    np.max(upper_ci)
)

# Start slightly below the minimum observed case
y_lower = np.floor(y_min / 10000) * 10000

# Round up to the next 10,000
y_upper = np.ceil(y_max / 10000) * 10000

# Set y-axis limits
ax.set_ylim(
    y_lower,
    y_upper
)

# Y-axis ticks every 10,000
ax.yaxis.set_major_locator(
    MultipleLocator(10000)
)

plt.yticks(
    fontsize=12,
    fontweight='bold'
)

# ── Legend ────────────────────────────────────────────────────────────────────
plt.legend(
    loc='upper left',
    fontsize=12,
    prop={'weight': 'bold'}
)

plt.tight_layout()

# Save figures
plt.savefig(
    'fitted_curve_R0gt1.eps',
    format='eps',
    bbox_inches='tight'
)

plt.savefig(
    'fitted_curve_R0gt1.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

# ── Results summary ───────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("ESTIMATED PARAMETERS")
print("=" * 60)
print(f"  beta_h     = {beta_h_est:.8f}   (transmission rate)")
print(f"  kappa      = {kappa_est:.8f}   (HIV → AIDS progression rate)")
print(f"  delta_h    = {delta_h_est:.8f}   (AIDS removal/mortality rate)")

print("\nINITIAL CONDITIONS")
print(f"  S0         = {S0}")
print(f"  Ih0        = {Ih0_est:.4f}   (HIV-positive at t = 0)")
print(f"  Ia0        = {Ia0_est:.4f}   (AIDS patients at t = 0)")
print(f"  Ih0 + Ia0  = {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print("\nGOODNESS-OF-FIT")
print(f"  R-squared  = {r_squared:.8f}")

print("\nEPIDEMIOLOGICAL THRESHOLD")
print(f"  R0         = beta_h / (kappa + mu)")
print(f"             = {beta_h_est:.8f} / ({kappa_est:.8f} + {mu})")
print(f"             = {R0:.6f}")
print(f"  R0 > 1     : {'✓  YES — disease is endemic / spreading' if R0 > 1 else '✗  NO'}")

print("\nOBSERVED vs PREDICTED")
print(f"  {'Year':<6}  {'Observed':>10}  {'Predicted':>12}  {'Residual':>10}")
print("  " + "-" * 44)
years = df['Months'].dt.year.values
for yr, obs, pred in zip(years, observed_cases, IhIa_fit):
    print(f"  {yr:<6}  {obs:>10.0f}  {pred:>12.2f}  {obs - pred:>10.2f}")

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from scipy.optimize import differential_evolution, minimize
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

# =============================================================================
# HIV-AIDS Compartmental Model:  S → Ih (HIV Stage) → Ia (AIDS Stage)
#
# Fitting target  : observed Cases = Ih + Ia  (combined active prevalence)
# Initial total   : Ih0 + Ia0 = 96565  (enforced via fraction parameterisation)
# R0 constraint   : R0 = beta_h / (kappa + mu) > 1  (enforced by reparameterisation)
#
# Reparameterisation trick:
#   beta_h = (kappa + mu) * (1 + eps),  eps > 0
#   => R0 = 1 + eps  which is ALWAYS > 1 by construction
# =============================================================================

# ── Fixed demographic parameters ─────────────────────────────────────────────
Lambda = 1457392   # annual recruitment into susceptible population
mu     = 0.014   # natural background mortality rate
TOTAL_INIT = 96565   # total infected at baseline year (Ih0 + Ia0)
S0         = 104002887

# ── ODE system ───────────────────────────────────────────────────────────────
def seir_model(y, t, beta_h, kappa, delta_h):
    """
    Compartments:
      S  – Susceptible
      Ih – HIV-positive (not yet AIDS)
      Ia – AIDS stage
    """
    S, Ih, Ia = y
    N = S + Ih + Ia

    lambda_h = beta_h * (Ih + Ia) / N        # force of infection

    dSdt  = Lambda - (lambda_h + mu) * S
    dIhdt = lambda_h * S - (kappa  + mu) * Ih
    dIadt = kappa  * Ih  - (delta_h + mu) * Ia

    return [dSdt, dIhdt, dIadt]


# ── Objective function (reparameterised) ─────────────────────────────────────
def objective(params, t, observed):
    """
    Free parameters: [eps, kappa, delta_h, frac]
      eps     : R0 excess above 1  (R0 = 1 + eps,  eps > 0)
      kappa   : progression rate HIV → AIDS
      delta_h : AIDS-related mortality / removal rate
      frac    : fraction of TOTAL_INIT assigned to Ih0  (rest goes to Ia0)
    """
    eps, kappa, delta_h, frac = params

    # Recover beta_h so that R0 = 1 + eps  (always > 1)
    beta_h = (kappa + mu) * (1.0 + eps)

    Ih0 = frac         * TOTAL_INIT
    Ia0 = (1.0 - frac) * TOTAL_INIT

    y0 = [S0, Ih0, Ia0]

    try:
        sol = odeint(seir_model, y0, t,
                     args=(beta_h, kappa, delta_h),
                     mxstep=5000, full_output=False)
        predicted = sol[:, 1] + sol[:, 2]          # Ih + Ia at each time point
        sse = np.sum((observed - predicted) ** 2)
    except Exception:
        sse = 1e18

    return sse


# ── Load data ─────────────────────────────────────────────────────────────────
file_name = '/content/HIV_2010_2023.xlsx'   # <-- update path if needed
df = pd.read_excel(file_name)

df['Months'] = pd.to_datetime(df['Months'], format='%Y')
df = df.dropna(subset=['Months'])

min_year = df['Months'].dt.year.min()
df['YearsSinceMin'] = (df['Months'].dt.year - min_year) * 12

t              = df['YearsSinceMin'].values.astype(float)
observed_cases = df['Cases'].values.astype(float)

# ── Step 1: Global search with Differential Evolution ────────────────────────
# bounds for [eps, kappa, delta_h, frac]
bounds_de = [
    (0.01, 5.0),    # eps    → R0 = 1+eps ∈ [1.01, 6.0]
    (1e-4, 0.5),    # kappa
    (1e-4, 0.5),    # delta_h
    (0.01, 0.99),   # frac   (Ih0 = frac * 96565)
]

print("=" * 60)
print("Step 1: Global search via Differential Evolution ...")
print("=" * 60)
res_de = differential_evolution(
    objective,
    bounds_de,
    args=(t, observed_cases),
    seed=42,
    maxiter=2000,
    tol=1e-12,
    popsize=20,
    mutation=(0.5, 1.5),
    recombination=0.9,
    workers=1,
    disp=False          # set True to watch DE progress
)
print(f"DE complete.  Best SSE = {res_de.fun:.4f}")

# ── Step 2: Local refinement with L-BFGS-B ───────────────────────────────────
print("\nStep 2: Local refinement via L-BFGS-B ...")
res = minimize(
    objective,
    res_de.x,
    args=(t, observed_cases),
    bounds=bounds_de,
    method='L-BFGS-B',
    options={'maxiter': 10000, 'ftol': 1e-15, 'gtol': 1e-12}
)

# ── Recover final parameters ─────────────────────────────────────────────────
eps_est, kappa_est, delta_h_est, frac_est = res.x

beta_h_est = (kappa_est + mu) * (1.0 + eps_est)   # guaranteed R0 > 1
Ih0_est    = frac_est         * TOTAL_INIT
Ia0_est    = (1.0 - frac_est) * TOTAL_INIT
R0         = beta_h_est / (kappa_est + mu)         # = 1 + eps_est

# ── Final ODE simulation ──────────────────────────────────────────────────────
y0       = [S0, Ih0_est, Ia0_est]
solution = odeint(seir_model, y0, t,
                  args=(beta_h_est, kappa_est, delta_h_est),
                  mxstep=5000)

Ih_fit   = solution[:, 1]
Ia_fit   = solution[:, 2]
IhIa_fit = Ih_fit + Ia_fit

# ── Goodness-of-fit ───────────────────────────────────────────────────────────
ss_res    = np.sum((observed_cases - IhIa_fit) ** 2)
ss_tot    = np.sum((observed_cases - np.mean(observed_cases)) ** 2)
r_squared = 1.0 - ss_res / ss_tot

# ── RMSE and 95% Confidence Interval ─────────────────────────────────────────
rmse = np.sqrt(np.mean((observed_cases - IhIa_fit) ** 2))

# Approximate 95% CI based on RMSE
ci = 1.96 * rmse

lower_ci = IhIa_fit - ci
upper_ci = IhIa_fit + ci

# Avoid negative values in the lower confidence limit
lower_ci = np.maximum(lower_ci, 0)

# Final fitted active cases
final_fitted_cases = IhIa_fit[-1]


# ── Plot ──────────────────────────────────────────────────────────────────────
plt.figure(figsize=(10, 6))

plt.plot(
    df['Months'],
    observed_cases,
    'go',
    label='Observed Cases',
    ms=7
)

plt.plot(
    df['Months'],
    IhIa_fit,
    'r-',
    label='Fitted Curve',
    linewidth=2.5
)

# 95% Confidence Interval
plt.fill_between(
    df['Months'],
    lower_ci,
    upper_ci,
    color='gray',
    alpha=0.35,
    label='95% CI'
)

plt.xlabel(
    'Year',
    fontsize=12,
    fontweight='bold'
)

plt.ylabel(
    'Active Cases ($I_H + I_A$)',
    fontsize=12,
    fontweight='bold'
)

# ── X-axis ────────────────────────────────────────────────────────────────────
ax = plt.gca()

# Set x-axis limits from 2010 to 2024
ax.set_xlim(
    pd.Timestamp('2009-06-06'),
    pd.Timestamp('2023-06-06')
)

# Show every year from 2010 to 2024
tick_dates = pd.date_range(
    start='2010-01-01',
    end='2023-01-01',
    freq='YS'
)

ax.set_xticks(tick_dates)

# Display labels as 2010, 2011, ..., 2023, 2024
ax.set_xticklabels(
    [date.strftime('%Y') for date in tick_dates],
    rotation=45,
    fontsize=10,
    fontweight='bold'
)

# ── Y-axis: automatically extend according to data and CI ─────────────────────
# ── Y-axis: start near the observed minimum and extend above maximum ──────────
from matplotlib.ticker import MultipleLocator

# Find the minimum and maximum values including the 95% CI
y_min = min(
    np.min(observed_cases),
    np.min(IhIa_fit),
    np.min(lower_ci)
)

y_max = max(
    np.max(observed_cases),
    np.max(IhIa_fit),
    np.max(upper_ci)
)

# Start slightly below the minimum observed case
y_lower = np.floor(y_min / 10000) * 10000

# Round up to the next 10,000
y_upper = np.ceil(y_max / 10000) * 10000

# Set y-axis limits
ax.set_ylim(
    y_lower,
    y_upper
)

# Y-axis ticks every 10,000
ax.yaxis.set_major_locator(
    MultipleLocator(10000)
)

plt.yticks(
    fontsize=12,
    fontweight='bold'
)

# ── Legend ────────────────────────────────────────────────────────────────────
plt.legend(
    loc='upper left',
    fontsize=12,
    prop={'weight': 'bold'}
)

plt.tight_layout()

# Save figures
# plt.savefig(
#     'fitted_curve_R0gt1.eps',
#     format='eps',
#     bbox_inches='tight'
# )

# plt.savefig(
#     'fitted_curve_R0gt1.png',
#     dpi=300,
#     bbox_inches='tight'
# )

plt.show()

# ── Results summary ───────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("ESTIMATED PARAMETERS")
print("=" * 60)
print(f"  beta_h     = {beta_h_est:.8f}   (transmission rate)")
print(f"  kappa      = {kappa_est:.8f}   (HIV → AIDS progression rate)")
print(f"  delta_h    = {delta_h_est:.8f}   (AIDS removal/mortality rate)")

print("\nINITIAL CONDITIONS")
print(f"  S0         = {S0}")
print(f"  Ih0        = {Ih0_est:.4f}   (HIV-positive at t = 0)")
print(f"  Ia0        = {Ia0_est:.4f}   (AIDS patients at t = 0)")
print(f"  Ih0 + Ia0  = {Ih0_est + Ia0_est:.2f}   (= {TOTAL_INIT} total infected)")

print("\nGOODNESS-OF-FIT")
print(f"  R-squared  = {r_squared:.8f}")

print("\nEPIDEMIOLOGICAL THRESHOLD")
print(f"  R0         = beta_h / (kappa + mu)")
print(f"             = {beta_h_est:.8f} / ({kappa_est:.8f} + {mu})")
print(f"             = {R0:.6f}")
print(f"  R0 > 1     : {'✓  YES — disease is endemic / spreading' if R0 > 1 else '✗  NO'}")

print("\nOBSERVED vs PREDICTED")
print(f"  {'Year':<6}  {'Observed':>10}  {'Predicted':>12}  {'Residual':>10}")
print("  " + "-" * 44)
years = df['Months'].dt.year.values
for yr, obs, pred in zip(years, observed_cases, IhIa_fit):
    print(f"  {yr:<6}  {obs:>10.0f}  {pred:>12.2f}  {obs - pred:>10.2f}")